### ISSUE TITLE
Everything in the NetCore.App nuget packages needs to be R2R

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#1550]
We need a test to ensure it too.

**Comment by ericstj** [comment]
Same as https://github.com/dotnet/corefx/issues/14595

**Comment by gkhanna79** [comment]
@ericstj Is this done?

**Comment by ericstj** [comment]
No, I did the bulk of the infrastructure, but it needs to be plumbed into official builds so that signing happens correctly.  I passed it off to @chcosta for that since its dependent on his core-setup infrastructure work.

**Comment by ericstj** [comment]
Self-assigning.  @chcosta and I will need to work on this together.

**Comment by ericstj** [comment]
Copied from corefx issue:
I've gotten part of the way there: ericstj/core-setup@1693be3

The change I've made so far runs cross-gen on the binaries that we pick up from other repos. The remainder of the work is to plumb an entry point to these depprojs so that they can be built after the host and before signing. Then update the host signing to also sign the cross-gen'ed bits. After doing that the packaging should be made to build without rerunning cross-gen (eg: /p:BuildPackageLibraryReferences=false). Then delete all the shared-framework cross-gening and signing.

I'm going to try to do more of the msbuild-side of plumbing now that @chcosta has finished the transition.  Ideally once I'm done with this we'll have an entry-point that does both host build and cross-gening.  I'll update the signing step to handle both of these outputs and I'll delete the signing phase for shared-framework.  Once this is done then @chcosta can help with updating all the builddefinitions to make the new sequence work.

**Comment by ericstj** [comment]
Fixed with https://github.com/dotnet/core-setup/pull/2244
