### ISSUE TITLE
UAC prompt UI of .NET Core Runtime Bundle should display product details

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1557]
1) Run the Bundler generated by official build.
2) The UI displayed under the UAC prompt does shows the branch/architetcure instead of product name.

@rakeshsinghranchi and @vivmishra Another one to look into.

**Comment by gkhanna79** [comment]
Once we understand this, we should port the fix to 1.0.x and 1.1.x as well.

**Comment by rakeshsinghranchi** [comment]
In 2.0.0 packages, UAC shows bundle exe name. Build definition for 2.0.0 uses microbuild for signing step. It does not expose ProductName field under advanced section. Also, looked at the msbuild SignFile task and it doesn't provide option to pass signtool.exe '/d' equivalent argument . This needs further follow up with MSBuild team for SignFile task. Note, this issue is common across the board , checked in SDK bundle and Runtime bundles.

**Comment by gkhanna79** [comment]
@chcosta @dagood Do you have suggestions on how to fix this?

CC @wtgodbe

**Comment by dagood** [comment]
I don't, maybe @crummel?

**Comment by crummel** [comment]
We didn't end up having to do this, but Barry said the MicroBuild team is very open to adding signing methods, they could probably add a version of this that passes the "/d" argument.  I'd probably start with the microbuild alias.

**Comment by rakeshsinghranchi** [comment]
Issue doesnot repro anymore in the latest daily builds produced  : https://dotnetcli.blob.core.windows.net/dotnet/master/Installers/Latest/dotnet-win-x64.latest.exe .
