### ISSUE TITLE
Native DLL's used through platform invoke arent loaded from AppContext.BaseDirectory

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1636]
@piotrpMSFT commented on [Thu Feb 09 2017](https://github.com/dotnet/coreclr/issues/9447)

Moved from https://github.com/dotnet/cli/issues/5622 on behalf of @PurelySimple. There are more details in the original issue.

 @yizhang82

----

## Steps to reproduce
1. Create a new console project (ie MyApp) that outputs `Console.WriteLine(AppContext.BaseDirectory);`
2. Reference a native DLL call on a method using `[DllImport("MyNative.dll")]`
3. Make a call to that method in the application
4. Run `dotnet build` on the project
5. Copy MyNative.dll to the output directory (ie bin\Debug\netcoreapp1.1)
6. Run `dotnet <MyApp.dll>` from **within the output directory**. Everything should work fine. AppContext.BaseDirectory will be the output folder.
7. Go to another location (such as the project root) and run `dotnet <path\to\MyApp.dll>`
8. Failed to find MyNative.dll but AppContext.BaseDirectory will still be correctly set as the output folder (which contains the native dll).
## Expected  behavior
I would expect any native DLL's referenced from an assembly to reside along side it and behave like other managed DLL's by being loaded from AppContext.BaseDirectory and not wherever the `dotnet path\to\app.dll` was invoked from.

This is especially problematic as VS2017 seems to invoke the compiled app DLL from the project root and not the bin\Debug\netcoreapp1.1\ directory where it resides. I have to keep a separate set of native DLL's in the project root for them to be found.

## Actual behavior
The platform invoke call throws an exception saying the native DLL couldn't be found.

## Environment data
`dotnet --info` output:

$ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by ramarag** [comment]
@PurelySimple please try this scenario again with 1.0 tooling. This appears to have been resolved there.
If you are still facing this issue please feel free to reopen the issue
https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/

**Comment by PurelySimple** [comment]
@ramarag I am able to verify that the 1.0 tooling fixes the above reproduction steps.

However, if the native DLL depends on another native DLL (secondary dependency) that is not referenced in the managed project, it will not successfully load the dependency even though it resides in the same directory as all the other DLL's.

Is it better to reopen and add this caveat or open a new issue? Thanks again.

**Comment by gkhanna79** [comment]
> if the native DLL depends on another native DLL (secondary dependency) that is not referenced in the managed project, it will not successfully load the dependency

Is the second native DLL in the same nuget package as the first native DLL? If so, i would expect it to be present in app.deps.json.

CC @eerhardt

**Comment by ramarag** [comment]
@gkhanna79 this issue is not consuming native assets from nuget packages.
@PurelySimple  copies over the native binaries to the bin folder and expects the app to consume it.

@PurelySimple the host is not in charge of the policy to load the native dlls which are copied over, 
Can you explain how the secondary dependency is being used by the native DLL. 
Can you provide the repro ?
Did you try the same on desktop/mono did it work?

if so file a new issue and I believe it should go to https://github.com/dotnet/coreclr

**Comment by gkhanna79** [comment]
> this issue is not consuming native assets from nuget packages.

@ramarag My point is that the host only consumes native components that are specified in the app.deps.json and is the reason why copying over will not work. thus, any secondary dependency needs to be in the nuget package as well.

**Comment by ramarag** [comment]
@gkhanna79 
The unamanged native binary loading is handled by the OS, coreclr just calls into the OS to load it. The OS is in fact responsible for loading the native binary's dependency. So listing it the deps file will not be useful unless it is loaded before the current binary in question

@PurelySimple does this make sense to you?

**Comment by gkhanna79** [comment]
That path  (in nuget package) is not something that LoadLibrary will search as it is not an app path.



Thanks,
Gaurav


-------- Original message --------

**Comment by PurelySimple** [comment]
@ramarag The secondary dependency is a plugin library that is loaded via [LoadLibrary()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx) with a relative path from the primary dependency.

From my understanding, [Windows DLL load order](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx) should follow this behavior:
`The directory from which the application loaded.
The system directory. Use the GetSystemDirectory function to get the path of this directory.
The 16-bit system directory. There is no function that obtains the path of this directory, but it is searched.
The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
The current directory.
The directories that are listed in the PATH environment variable. Note that this does not include the per-application path specified by the App Paths registry key`

For another OS, I can imagine the order and locations being different and from my understanding is why Mono uses [DLLMaps ](http://www.mono-project.com/docs/advanced/pinvoke/dllmap/)to locate a targeted set of DLL's. (Which sounds like what deps.json is accomplishing also).

I think the thing I'm most surprised about is that the hosting application does not add the directory of the application DLL as a default search path. If the target OS doesn't allow adding a search path but rather needs a list of DLL's, I would expect a way to specify those dependencies somewhere (preferably not by writing a post build script to inject them into deps.json).

I am going to do more testing with Nuget packages as that seems like everything I want and I think its the right path forward for a library you plan to distribute and others consume.

@gkhanna79 Should I expect LoadLibrary to work with files listed in deps.json?

**Comment by gkhanna79** [comment]
> The directory from which the application loaded.

Are you trying a portable app or standalone app? For the former, this is the path to dotnet.exe while latter, this will be path to app.exe which is actually containing all app binaries. Copying over in the standalone case would work since OS would find it in app's folder.

@PurelySimple Where is the secondary dependency coming from? Is it not next to the actual native binary that depends upon it? If not, then how will this scenario even work for standalone app since the secondary dependency will not be part of the app? 

To make it work correctly for all scenarios, your app's transitive closure should either be with app's dependencies or present in system wide locations.

LoadLibrary is agnostic of deps.json and should not worry about it. This issue is really around how the secondary dependency is packaged or deployed.

**Comment by PurelySimple** [comment]
@gkhanna79 I've built a lot of managed code around my native dependencies. My workflow as I develop it is a portable app as I can debug it faster but the end goal is a nuget package that other projects will consume and be built as standalone apps. The standalone build works great as all the dependency DLL's live in the same folder and I can distribute it on platforms just fine. Its the portable app that I use to debug and build upon that made me see this as an issue.

The secondary dependency lives along side all the other DLL's in the same folder as my output (bin/debug). If I have that secondary dependency DLL in the root of the project where VS invokes dotnet path/to/MyApp.dll everything works but it does not find the one in the output folder. Which is the same issue I had with the primary dependency before the 1.0 tooling.

**Comment by gkhanna79** [comment]
@PurelySimple Let me try to understand this better by giving some definitions to locations:

0) DotnetFolder - folder containing dotnet.exe (e.g. PF(x86)\dotnet)
1) ProjFolder - folder containing source files of your portable app
2) bin/Debug - Folder where dotnet build places the app binaries post build
3) bin/debug/netcoreapp1.0/debug - Folder where dotnet publish places the app binaries, and its dependencies, post publish operation.

Do I understand it correct that if the secondary native dependency binary is present in ProjFolder, the app works using dotnet.exe from DotnetFolder but does not when the binary is present in (3) or (4) above? If so, what is your working directory when dotnet is invoked for both the passing and failing cases?

**Comment by yizhang82** [comment]
@gkhanna79 Can we document this somewhere? I've seen enough folks having trouble with this on .NET Core and we should publish a guidance doc for it. Perhaps @ramarag can write up something?

**Comment by gkhanna79** [comment]
I would like to understand the issue first before we writeup something.

**Comment by yizhang82** [comment]
@gkhanna79 Of course. :) However I"m also talking about the general question of "how do I make sure my native dependency gets loaded properly by the dotnet host".

**Comment by gkhanna79** [comment]
> "how do I make sure my native dependency gets loaded properly by the dotnet host".

They are already loaded if they are part of your nuget package since they are listed in the app.deps.json - nothing special is required.

**Comment by PurelySimple** [comment]
@gkhanna79 
> Do I understand it correct that if the secondary native dependency binary is present in ProjFolder, the app works using dotnet.exe from DotnetFolder but does not when the binary is present in (3) or (4) above? If so, what is your working directory when dotnet is invoked for both the passing and failing cases?

Using your definitions, let me clarify.
- (Fail Case)Copying all native DLL's (including the secondary dependency) into the bin/Debug folder post build and running dotnet bin/Debug/MyApp.dll from the ProjFolder, the secondary dependency DLL will not be found in 1.0 tooling.
- (Success Case # 1)Copying all native DLL's into the bin/Debug folder post build and running dotnet MyApp.dll from within the bin/Debug folder will find the secondary dependency DLL.
- (Success Case # 2)Copying all native DLL's into the bin/Debug folder AND the ProjFolder and running dotnet bin/Debug/MyApp.dll from the ProjFolder, will find and use the secondary dependency DLL in the ProjFolder.

The failure case is what happens by default when I press run in VS2017 for my project. If VS invoked dotnet from the bin/Debug folder instead of the ProjFolder, the first success case would happen. Alternatively, if dotnet.exe allowed the directory it was hosting (bin/Debug) to be on the search path for native DLL's it would also work.

Does that help?

**Comment by gkhanna79** [comment]
@PurelySimple Please see **Standard Search Order for Desktop Applications** section at https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx. All the cases enumerated above can be explained by the DLL search order. Specifically, when your "current working directory" does not contain the binaries, it fails but when it does, it passes.

> if the native DLL depends on another native DLL (secondary dependency) that is not referenced in the managed project, it will not successfully load the dependency even though it resides in the same directory as all the other DLL's.

I believe even if this is packaged within nuget package, any secondary dependency will not be found (unless there is a direct PInvoke being made to the secondary dependency for managed code). Can you confirm this secondary dependency is not part of any nuget package?

**Comment by PurelySimple** [comment]
@gkhanna79 I can confirm the secondary dependency is not part of any nuget package. I suppose I could add PInvoke bindings to my secondary dependency just to insure that it becomes a primary dependency and can be found in the bin/Debug directory (as of 1.0 tooling). It just circumvents the original intentions of the native library.

I am wrapping the widely popular [SDL2 Library](https://www.libsdl.org/) in .Net Core. One of its extension projects is SDL2_img which is a library for loading different image formats to be consumed by SDL2. I have .Net Core PInvoke bindings for this library (making it a primary dependency). This native library upon initialization attempts to load optional secondary DLL's via LoadLibrary (aka secondary dependency). If the library doesn't exist, you simply can't load images of that format. This is good for the user as they can choose what specific image formats they only care to load and not carry the overhead of an entire image loading library. Sounds very familiar to the principals of .Net Core doesn't it?

These secondary dependencies were never intended to interact with anything other than the primary dependency and must live in the same folder. Since dotnet.exe hosts another application (possibly in another directory), the OS makes the directory it's invoked from the default search path (as outlined in the search order link). In order to load first level dependencies in a directory other than the launch directory, it can load a configuration file which points the location of other libraries to load when needed (ie deps.json). The problem is that the OS has made the directory dotnet.exe is launched from, the default search directory for DLL's. If secondary dependencies are not in the same folder as where dotnet.exe is launched, they will never be found by the OS. The native DLL I PInvoke knows nothing of deps.json (and shouldnt) and so whether a secondary dependency is listed in there is irrelevant.

I was originally thinking there was a way to specify additional search directories from an application perspective but that's not possible and even if it were possible on one platform, it may not be on another. What IS possible is to make sure you ALWAYS invoke dotnet.exe from the same directory as the hosted application. Doing this via command line is straight forward and easy. However, this is NOT the default behavior of a .Net Core Console application in VS2017. The default behavior is to launch dotnet.exe from the ProjFolder. This means I have to resort to keeping secondary dependencies in my ProjFolder during development OR add my bin/Debug directory to PATH OR throw my secondary dependencies into System... etc. This is not ideal for debugging or development, especially if I want others to use my library and now they have to make sure secondary dependencies are in the appropriate location.

I hope this makes the problem very clear. The 1.0 tooling fixed the issue for primary dependencies (thank you!) and I've listed my workarounds for secondary dependencies. At this point I can work around it and you can decide how to prioritize it against other issues. Thanks again.
