### ISSUE TITLE
HostFXR.dll is published to Azure under SharedFX version

### ISSUE THREAD

**Issue by schellap** [dotnet/core-setup#181]
## Steps to reproduce

Download:
https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.1/dotnet-hostfxr-win-x86.1.0.1.zip

You get a 404.
## Expected  behavior

https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.1/dotnet-hostfxr-win-x86.1.0.1.zip
should succeed
## Actual behavior

https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0/dotnet-hostfxr-win-x86.1.0.1.zip
succeeds instead if we used the SharedFX version
## Environment data

`dotnet --info` output:

**Comment by schellap** [comment]
Fixed by #180

**Comment by gkhanna79** [comment]
Marking for RTM to understand if this is required.

**Comment by joshfree** [comment]
FYI @mellinoe

**Comment by gkhanna79** [comment]
Based upon offline discussion with @eerhardt, this is not required to be fixed for RTM. Thus, I am moving  the bug to 1.1.0 and closing the associated PR (https://github.com/dotnet/core-setup/pull/180).

**Comment by gkhanna79** [comment]
@eerhardt Can you remind me why we would want to fix this? What breaks if this is not fixed?

**Comment by eerhardt** [comment]
> @eerhardt Can you remind me why we would want to fix this? What breaks if this is not fixed?

This is kind of tricky IMO.  The issue here is that we have multiple versions of assets being built out of the same repo.  So the "shared framework" can be version `1234` and the "host" can be version `4321`.  When we publish assets for a single build, to me it feels like all the assets for that build should go to a single place.  But that makes it hard to go find those assets because when I'm looking for "host" version `4321`, I need to know the corresponding "shared framework" version `1234` to go find them.

I'm not certain what to do here. It would be easier if all the assets had the same version - or at least we had a single build number for the whole build where the assets could go.

**Comment by gkhanna79** [comment]
@eerhardt and I discussed this - we could go either way but it is slightly more straightforward to find host packages in the same folder as SharedFX since if the host changes, SharedFX would also version alongwith the host.

Also, since the repo will be undergoing changes regarding how it is built, changing this is not really helpful as that would throwaway.

Given this, I am closing the issue.
