### ISSUE TITLE
NETCore packages are being produced for both win10-x64 and win7-x64

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#1825]
We are producing packages for win10-x64 and win10-x86, when we should only be producing for win7 (or possibly just `win`):

See
https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win10-x64.Microsoft.NETCore.App
https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win10-x86.Microsoft.NETCore.App

/cc @ericstj @chcosta @gkhanna79

**Comment by ericstj** [comment]
I did this intentionally so we had runtime packages with a smaller layout: no API sets.  The API-sets aren't easily trimmable since they will always be referenced its just that they are inbox on Win10.

Also, perhaps with some recent changes to our toolset/pinvokes perhaps we no longer even need the API sets on win7.  @gkhanna79 can you clarify that?

**Comment by Petermarcu** [comment]
We dropped them completely from the shared framework that runs on all our supported windows platforms.

**Comment by gkhanna79** [comment]
Correct - we do not need APISets anymore.

**Comment by ericstj** [comment]
I see, https://github.com/dotnet/coreclr/commit/4f0753dce7402a2f9f51735292f07b6165989d17 removed that dependency.

In that case I agree, lets delete the extra packages.
