### ISSUE TITLE
Sign arm32/arm64 Windows binaries in build pipeline

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/core-setup#1977]
Today we only sign x64 & x86 - we should be signing arm32 & arm64 as well. This could be done as part of refactoring the pipeline .json blobs to use shared definitions.

CC @gkhanna79 @dagood @leecow @crummel

**Comment by gkhanna79** [comment]
We should get this in place before feature complete if we can.

**Comment by wtgodbe** [comment]
@MichaelSimons do you know of any reason we're not already doing this?

**Comment by MichaelSimons** [comment]
@wtgodbe - this is outside my realm.  @dagood, @crummel - can you answer Will's question?

**Comment by wtgodbe** [comment]
Also, does anyone know why the environment variable SIGNED_PACKAGES gets set in the x64 build (https://github.com/dotnet/core-setup/blob/master/buildpipeline/Core-Setup-Signing-Windows-x64.json#L461), but not in the x86 build?

**Comment by gkhanna79** [comment]
Is that a regression from the original change that brought in checked in build definitions for Core-Setup (e.g. https://github.com/dotnet/core-setup/commit/22e89978651525436965791f11613ebd0cb4edc6#diff-3867ee2c3921d2e2988404fcb10bb64e)?

I do not see SIGNED_PCKAGES in either 1.0.0 and 1.1.0 build definitions for WinX86.

@ravimeda What are your thoughts?

@wtgodbe Can you please take a look at the 1.1.2 binaries on myget to confirm if they are actually signed or not? Likewise for 1.0.5.

**Comment by wtgodbe** [comment]
@weshaggard do you know what SIGNED_PACKAGES is doing? looks like it's at least used here https://github.com/dotnet/core-setup/blob/69eeba979b44cee29b84cfd64193d838eb572c09/pkg/projects/Microsoft.NETCore.UniversalWindowsPlatform/Microsoft.NETCore.UniversalWindowsPlatform.pkgproj#L17, along with a couple of other places

**Comment by dagood** [comment]
If things haven't changed, setting `SIGNED_PACKAGES` in only one build leg is intentional--it's an indicator of the single build that should publish its managed NuGet packages, to avoid builds overwriting each other. It's not (afaik) an indicator of whether or not the build attempts to sign its binaries.

I believe the name is `SIGNED_PACKAGES` because previously only one build leg signed its packages, and therefore it was the one that needed to publish them. Other build legs had `SIGNED_PACKAGES=false` to avoid overwriting the signed packages with their unsigned packages. Now that both x64 and x86 sign their binaries, but still only one publishes them to avoid overwrites, the name is confusing.

(Disclaimer: this info is from a bug investigation months ago.)

**Comment by crummel** [comment]
SIGNED_PACKAGES appears to be informative rather than directive; it's read [here](https://github.com/dotnet/core-setup/blob/50f02306d151453edefac602934f480b27cb7209/build_projects/dotnet-host-build/PublishTargets.cs#L337) to determine whether to publish packages, and [here](https://github.com/dotnet/core-setup/blob/69eeba979b44cee29b84cfd64193d838eb572c09/pkg/projects/Microsoft.NETCore.UniversalWindowsPlatform/Microsoft.NETCore.UniversalWindowsPlatform.pkgproj#L17) and [here](https://github.com/dotnet/core-setup/blob/9f1af7fc92ab1df20026c3eace8183481df5df8f/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj#L18) to determine whether to turn `IncludeAllRuntimePackagesInPlatformManifest` on, but I can't find anything that depends on that.  If x86 is signing packages, it's probably most correct to set it in that build definition as well.

I don't know of any reason we can't sign the ARM binaries, MicroBuild has certificates that it specifically calls out for ARM so those should work.

**Comment by gkhanna79** [comment]
I added support in Core-Setup to produce portable RID builds in https://github.com/dotnet/core-setup/commit/62c26d8405661d0bae21ad78544e7681644ab08b. As a result, the Windows-X64 Signing build definition is used twice:

1) Once for non-portable build
2) Once for portable build (in https://github.com/dotnet/core-setup/commit/62c26d8405661d0bae21ad78544e7681644ab08b#diff-c9539d529b27144215b930ab94c59342R159)

Does this mean that I should update Portable build definition to specify SIGNED_PACKAGES to false?

**Comment by dagood** [comment]
Yes--having it true there might actually explain at least part of https://github.com/dotnet/core-setup/issues/1994 (package overlap), although there's more investigation I'm doing there to know for sure.

**Comment by wtgodbe** [comment]
Solved by https://github.com/dotnet/core-setup/pull/2477
