### ISSUE TITLE
Installer for Mac OSX should be self-contained and not require brew / openssl

### ISSUE THREAD

**Issue by mmc41** [dotnet/core-setup#200]
The current installer for Mac says this "In order to be able to use .NET Core on OS X, you need to install OpenSSL version 1.0.1/1.0.2. There are many ways to install/update your libssl. Using Homebrew is the easiest. You can view the instructions here or if you're updating, on this page."

It is quite a hurdle to get brew installed and opensll updated. For me both failed. First brew failed updating, and then after reinstalling brew, it reported errors trying to install openssl.

The .net core installer should contain anything - and absolutely not require usage of brew!!

**Comment by bluemmc** [comment]
Dot net core on Mac should embed dependencies like OpenSSL. Otherwise self-contained application (XCOPY deployment) will NOT work as advertised

**Comment by joshfree** [comment]
@blackdwarf @bartonjs @Priya91

**Comment by wjk** [comment]
I stumbled upon this issue just now and decided to add my 2¢. I wholeheartedly agree with @bluemmc regarding the XCOPY deployment, which was one of the greatest features of .NET Core to begin with. Checking the build script for this library in question in corefx reveals that [it uses `install_name_tool` to search for libcrypto/libssl in the same directory as the corefx dylib](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Security.Cryptography.Native/CMakeLists.txt#L81-L91). @joshfree Is there any reason why we can’t simply update the OSX installer to use this strategy? I could prepare a PR with these changes if desired.

**Comment by bartonjs** [comment]
@wjk There are two conflicting models at play here:

1. Don't have external dependencies / be xcopyable
2. Security updates to cryptographic components should apply without re-releasing a product

Let's say a new vulnerability is found in TLS (happens every couple of years).  By using loose dynamic linking whenever the system copy gets upgraded (via brew, apt-get, emerge, et cetera) then .NET projects benefit from this change.  If it's an xcopy situation then all of the copies need to get overwritten again.  And if the binary is being distributed as a 3rd party binary by an installer... well, that installer needs to be updated and everyone who has ever used it needs to update that particular component.

For most of the platforms we run on we use the normal system cryptography library.  On Windows we use CNG and SChannel; on the various Linux distributions we use OpenSSL as managed by a package manager.  macOS is in a unique state because there we're using an alternate cryptographic library; and due to how things have evolved over time it is now difficult to "install" that library.

The current position we are taking is that we don't want to be in the way for customers to get security updates from OpenSSL; so we don't want to bundle it in our installer.  If an application built with .NET Core wants to bundle OpenSSL with it, that application will be xcopy deployable (because we include the loaded-from directory in the search path). But if the application wants to maintain the "I upgrade this security component once and everyone benefits" strategy that .NET Core itself maintains, that'll work, too.

Long term we're looking to get off of OpenSSL on macOS, using CommonCrypto/SecurityTransforms/SecureTransport.  The macro-issue for that is dotnet/corefx#9394, which shows that we've already started chipping away at the OpenSSL dependencies; but it does remain a work-in-progress.

**Comment by eerhardt** [comment]
This should be fixed in 2.0 now, right?  On macOS, we are no longer requiring OpenSSL.

**Comment by bartonjs** [comment]
@eerhardt Yup, that's been done for a couple weeks now.  I don't know if anything in the setup experience needs to be adjusted because of that, so I'll leave this for you to close.

**Comment by eerhardt** [comment]
Looks like there is some installer work that needs to be undone.

https://github.com/dotnet/core-setup/blob/eca152525e19a41d489cd5845afa14982653cc0a/packaging/osx/sharedframework/scripts/postinstall#L13

**Comment by blackdwarf** [comment]
@eerhardt yup, the checks and whatnot need to be removed. :)
