### ISSUE TITLE
Reduce occurences of build publishing race condition

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2081]
We are occasionally hitting this failure in our official builds

> From: Davis Goodin 
Sent: Monday, April 17, 2017 9:49 AM
To: dotnet-bot <dn-bot@microsoft.com>; .NET Core Builds <dncbuilds@microsoft.com>
Subject: RE: DevDiv Build 20170417-04 failed
Looking into this. At first glance, it’s a publish semaphore locking issue, which is normally caused by two builds happening too close together:
Build failed: System.Exception: Unable to acquire lease on master/Binaries/sharedFxPublishSemaphore
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=682013

I’d think this could be avoided  by moving this code, https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/PublishTargets.cs#L89, around a bit to something more like

``` C#
                string leaseId;

                // Prevent race conditions by dropping a version hint of what version this is. If we see this file
                // and it is the same as our version then we know that a race happened where two+ builds finished 
                // at the same time and someone already took care of publishing and we have no work to do.
                if (AzurePublisherTool.IsLatestSpecifiedVersion(targetVersionFile))
                {
                    return c.Success();
                }
                else
                {
                    leaseId = AzurePublisherTool.AcquireLeaseOnBlob(semaphoreBlob);

                    Regex versionFileRegex = new Regex(@"(?<CommitHash>[\w\d]{40})");
```

**Comment by dagood** [comment]
Doesn't this introduce the race condition again?

I'm also not sure if this solves the issue because the code here is for multiple build legs of the same pipebuild finishing at the same time. (Comment terminology is outdated.) The build issue is when multiple builds of different pipebuilds (different commits) finish at the same time, and are both are in that `else` block.

**Comment by chcosta** [comment]
I titled the issue "reduce", not "eliminate".  I think this would help reduce the occurrences where we try to acquire a lease but are already on the specified version.  You're right, this would only apply to the current Pipebuild instance.  For fixing multiple pipebuild instances (multiple commits merged close together), we'd probably have to do something with how maestro schedules jobs.  

I think it will take quite a bit of testing to determine if this would make the situation better or worse.  I'm completely ok with closing this if the current logic is a non-issue for build legs within the same pipebuild instance.

**Comment by chcosta** [comment]
@dagood has more experience investigating the semaphore locking issues and hasn't really seen them as an issue for within a single PipeBuild instance.  I'll close this issue for now.

**Comment by dagood** [comment]
I ask if it would introduce it again because currently this semaphore is used here to make sure two build legs don't try to start publishing at the same time--it's a fix for a race condition. After the change suggested above, I can see this happening:

 * Legs A and B complete at the same time, and both see that all legs are done building.
 * Legs A and B check targetVersionFile to see if another leg has started publishing.
   * No: they both enter the `else`.
 * Leg A locks the semaphore. Leg B waits.
 * Leg A publishes everything (to Latest folder, to MyGet, etc).
 * Leg A unlocks the semaphore.
 * Leg B locks the semaphore.
 * Leg B publishes everything. <- Bad, will fail any immutable destinations, and doubles the publish time.
 * ...

As it is now, locking before checking targetVersionFile lets B see that A has already published for this commit, so it just returns success after it gets the lock. It's true that B is blocked on A completing before it can check the file, but this isn't a problem.
