### ISSUE TITLE
Need to set SIGNED_PACKAGES on portable windows builds

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2136]
Today, we have 2 flavors of windows builds: portable `win7-arch` and non-portable `win-arch`.

Our plan is to ship the non-portable builds. We are already consuming the portable builds in the .NET Core SDK.

However, we are not setting the `SIGNED_PACKAGES` build variable in our portable builds.  This is a problem because we are using that variable here:
https://github.com/dotnet/core-setup/blob/9f1af7fc92ab1df20026c3eace8183481df5df8f/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj#L14-L18

This code is necessary to build the correct manifest file in the `Microsoft.NETCore.App` nuget package.

We are lucking out today that the non-portable build takes longer (because it is signed), so it will overwrite the portable build's package.  But when we start signing the portable build (or turning off the non-portable build completely), we are going to have issues.

@gkhanna79 @ericstj

**Comment by gkhanna79** [comment]
I asked this to @ericstj in email as well. What all legs need this to be defined? Based upon the description, I would assume, atleast, all Windows legs need to have it, right? What if, in future, a non-Windows leg takes the longest and attempts to perform the publish. Should it be defined for those as well?

**Comment by ericstj** [comment]
/cc @chcosta 

This was merely done as a hack.  Better yet would be to just define the property on the leg we want to ship the identity package.  That's what I suggested when I initially added it. https://github.com/dotnet/core-setup/commit/4772778ba76f51abeaa01973f6c33e91cc3de530

>In the future we need to make sure that if we switch the official
build to be completely vertical we still have a build-leg that will
run after all verticals of dependencies are complete to build the
RID-less package for Microsoft.NETCore.App.

**Comment by chcosta** [comment]
Wouldn't this still be a problem for building the manifest because of what Gaurav mentioned?  

> What if, in future, a non-Windows leg takes the longest and attempts to perform the publish

**Comment by gkhanna79** [comment]
And I am pretty sure we are going to have a change soon that will make non-Windows leg run the longest (that change is temporarily pulled out for other reasons).

What is the right fix for this @ericstj ?

**Comment by ericstj** [comment]
When this change was made I discussed with @eerhardt and @dagood and was directed that I should use SIGNED_PACKAGES and that this property was the one that was **already designated** to ship any package which may have overlapped with a package produced from another leg.  The things you're saying about "take the longest" did not enter the discussion as far as I recall.  The impression I got was that the core-setup build legs pushed to leg-specific paths in Azure then the one designated with SIGNED_PACKAGES was the one that would be preferred, regardless of which leg actually preformed the publish.  I liked this because it keeps our source tree clean and doesn't require us to do extra gymnastics to support vertical build (every platform needs platform-agnostic assets) vs official build (we can only ship one set of platform agnostic-assets).  That's why I recommended we take a similar approach for corefx: https://github.com/dotnet/corefx/issues/16126.

The right fix is one of two things:
1. Ensure that the SIGNED_PACKAGES designation is assigned to a single leg (consider renaming the property to PRIMARY_PUBLISH_LEG or something) and ensure that this is honored by publishing regardless of which leg does the publishing.
2. Create some other designation for the leg responsible for shipping platform-agnostic packages and plumb that through the build-definitions and package build, including legacy core-setup build of IL-packages, so that only one leg produces any given package.

**Comment by gkhanna79** [comment]
Today, SIGNED_PACKAGES is set only for Windows X64 build and is used for two cases:

1) Publish the DependencyModel and RuntimeAbstraction packages (see https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/PublishTargets.cs#L348)

2) Used for the scenario Eric called out above that expects all RID specific artifacts to have been published by then.

Today, the invariant for (2) is held by Windows X64 leg since it is not only having this flag set in the build definition but also is the longest running leg that does the final publish. As a result, by that time all RID specific artifacts are expected to have been completed and thus, the system works today.

IIUC, an approach to address this would be to make the Windows X64 build definition be its own pipeline/definition that depends upon all other definitions to complete first. As a result, it will be ensured that all RID specific artifacts have been built. 

Thoughts?

**Comment by gkhanna79** [comment]
CC @wtgodbe who can help with the build definition change.

**Comment by wtgodbe** [comment]
Here's the PR for the suggested change - https://github.com/dotnet/core-setup/pull/2142

**Comment by eerhardt** [comment]
I think @ericstj's #2 is the right way above.

A little background:

For both the dotnet/cli and dotnet/core-setup repos, we use a model where all legs of the build run at the same time.  When each leg finishes, it uploads its built assets to azure storage, then checks to see if it is the ["last leg" to finish](https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/PublishTargets.cs#L79-L82). If it is, it "finalizes the build".

"Finalizing the build" does:
1. Copies all the legs' (others' and itself's) assets to the "latest" folder.
2. Publishes the "core host" packages to myget.  Again, some assets get built by other legs, some by it.

The way uploading the "managed nuget" packages work is separate from this "finalize the build" step.  Each leg checks for this `SIGNED_PACKAGES` variable during it's publish, and if it is set (and it is Windows), the "managed nuget" packages get pushed to myget and to the azure blob storage.

I think we should handle the identity (non-RID) "core host" nuget packages the same way.  Obviously I agree with @ericstj that was should name this variable better than `SIGNED_PACKAGES`.  But the idea that we mark a single leg as the "upload the non-runtime-specific assets" leg makes a ton of sense. All legs still upload/publish the runtime-specific assets they are responsible for - because they are the only one that can produce them.  But then one leg is marked to do the non-runtime-specific ones as well.

The FinalizeBuild still does what it does - the last leg finished pushes everything to the final spots.

**Comment by gkhanna79** [comment]
Per Eric's comment in his commit, he mentioned that the identity package needs to be built once all rid specific assets can be restored and downloaded.

Did I misunderstand it? If not, then wouldnt the leg needing to wait for all rid specific assets end up being blocked until they are available, and making the build do finalization as well?


Thanks,
Gaurav
________________________________

**Comment by ericstj** [comment]
If you want to go with option 2 then we need to plumb through a convention for building identity packages like I did in corefx.
https://github.com/dotnet/corefx/blob/b7153b2f56f1a3dd49a67d4eca7dd78c791e8539/pkg/dir.traversal.targets#L6-L12

If we do that then we can use ShouldBuildIdentityPackage in the same way I'm using SIGNED_PACKAGES today.  In CoreFx we had the AllConfigurations leg to designate as the source of identity packages.  No such leg exists in core-setup so we should probably choose one of the legs and have it pass in ShouldBuildIdentityPackage or something like that.

**Comment by ericstj** [comment]
Actually option-2 isn't going to work well in core-setup without additional work.  Tests and shared framework publishing rely on having identity packages produced in all legs.  You need to do the filtering at publish time.
