### ISSUE TITLE
Remove portable suffix from all publishing artifacts

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#2261]
As of today, packages built are suffixed with "-portable". This includes tars,zips and installers

**Comment by rakeshsinghranchi** [comment]
This suffixes the product name with "-portable"
https://github.com/dotnet/core-setup/blob/release/2.0.0/build_projects/dotnet-host-build/PrepareTargets.cs#L291

**Comment by gkhanna79** [comment]
@Petermarcu do we care about producing Distro-RID specific artifacts anymore? If not, then we need to switch to simply making builds to be portable (i.e. produce win/osx/linux-<arch>) for all cases (Official, CI, end-developers) and have installers to be similarly named.

CC @leecow @eerhardt

**Comment by Petermarcu** [comment]
Two things. I think for now, the only thing we need to build is portable and that we should just switch. We need to make sure the build can still build distro specific and in the future, we may need to build for a specific distro and need to make sure the plumbing is still all there. Alpine is a good example of where we will need to do distro specific. I believe FreeBSD would also be in the boat.

**Comment by eerhardt** [comment]
FYI - this is fixed in 'master'.

The reason we were using `-portable` in our assets was to avoid conflicts (we had windows and macOS assets with different contents, but trying to write to the same files).  In the future, when building for distro-specific, we should be using distro-specific RIDs in the asset name.  That will avoid conflicting file names, and we won't need to use `-portable` or any other sort of suffix.

**Comment by Petermarcu** [comment]
So can this be closed?

**Comment by rakeshsinghranchi** [comment]
Yes. Closing this now.
