### ISSUE TITLE
Remove /t:GenerateVersionSourceFile from our official builds

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2265]
In all our official builds we have a step like the following:

```
"filename": "$(PB_SourcesDirectory)/Tools/msbuild.sh",
"arguments": "$(PB_SourcesDirectory)/build.proj /t:GenerateVersionSourceFile /p:GenerateVersionSourceFile=true /p:OfficialBuildId=$(OfficialBuildId)",
```
See https://github.com/dotnet/core-setup/blob/571fdf07301ed6367890fac3812cd87c0998c8d3/buildpipeline/Core-Setup-OSX-BT.json#L88

Looking into what this target does:

https://github.com/dotnet/buildtools/blob/03988127f489bcd1cf58d71131ac628620d53de9/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L181-L186

1. The comment in the code says it is for non-Windows, yet we have it for Windows builds.
2. core-setup doesn't use the outputted `$(NativeVersionSourceFile)`.

This is a waste and clutters our build definitions.  We should remove these steps. We shouldn't have them just because other repos need them, or because "we might need them in the future". If we need it in the future, we will can add it then.

And with removing this, I think we can remove the "init-tools" calls before it as well.

**Comment by chcosta** [comment]
We should probably change the step to call the `CreateVersionFileDuringBuild` target.  I think that's the real intent.  We need the version file to be created so that we produce the `BuildVersion.props` file which defines the buildtools versioning `BuildVersionMajor` and `BuildVersionMinor`.  I don't think it's hurting anything as-is, but i'll look into changing this after some of the other stabilization work has quieted.

**Comment by chcosta** [comment]
I see that the "CreateVersionFile" target is now a build dependency in build.proj.  That would indeed make this target irrelevant.
