### ISSUE TITLE
Some HostActivationTests do not work with the 2.0 host

### ISSUE THREAD

**Issue by mellinoe** [dotnet/core-setup#2273]
Three test cases here assume that various paths will be returned from `PackageCompilationAssemblyResolver.GetDefaultProbeDirectories` when set as environment variables:

https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/src/test/Microsoft.Extensions.DependencyModel.Tests/PackageResolverTest.cs#L23

However, [that method](https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/src/managed/Microsoft.Extensions.DependencyModel/Resolution/PackageCompilationAssemblyResolver.cs#L41-L56) will not return any paths defined in environment variables if the `PROBING_DIRECTORIES` property is set on the AppContext. This is the case when using the 2.0 host, although it was not in 1.0. We need to modify these tests to handle the behavior for .NET Core 2.0.

@ramarag @eerhardt

**Comment by mellinoe** [comment]
My current PR (#2259) has these tests disabled right now.

**Comment by gkhanna79** [comment]
@eerhardt @ramarag Is this a breaking change in 2.0 DependencyModel?

**Comment by eerhardt** [comment]
> Is this a breaking change in 2.0 DependencyModel?

Yes and no.  Technically yes this was a change that DependencyModel would always probe the `NUGET_PACKAGES` folder for compilation assemblies, even if the host wouldn't be looking in that folder.

Today, if the host tells DependencyModel where it is looking, then DependencyModel will only look in those places.  It won't explicitly check `NUGET_PACKAGES`.

In normal cases during `dotnet run`, the host will look in `NUGET_PACKAGES` because it was supplied to `--additional-probing-paths`.  So there is no mainline scenario breaking change here.

But if some edge case scenario set NUGET_PACKAGES only for DependencyModel to probe that directory, then yes, they would be broken.  The fix would be to supply the path using `--additional-probing-paths`, just like how you tell the host to look in directories.

**Comment by gkhanna79** [comment]
Given the above, is the plan to switch to use additional-probing-paths instead of nuget packages envvar?

**Comment by eerhardt** [comment]
We are already using additional-probing-paths instead of NUGET_PACKAGES when running using the 2.0 dotnet host.  We left the fallback check for NUGET_PACKAGES in for the case where DependencyModel 2.0 is being used outside of the 2.0 dotnet host (either in the 1.x host or on desktop).

The tests in question were explicitly setting NUGET_PACKAGES to some random location and expecting DependencyModel to honor it, which was true when the tests were run using the 1.x dotnet host.  But when we switched them to run with the 2.0 host, DependencyModel was no longer honoring this env var, since the 2.0 host was passing the probing paths.

We've changed the tests to expect the new behavior.

@gkhanna79 - one question for you - is it possible to change/mock `AppContext.GetData` for unit tests?  That would help us be able to isolate the behavior we want to test here.  I don't see an `AppContext.SetData` method.  I see a `SetSwitch`, but that only allows boolean values.

**Comment by gkhanna79** [comment]
@AlexGhiondea Do you have suggestions on how to do AppContext.SetData?

**Comment by gkhanna79** [comment]
@eerhardt What are the next steps here?

**Comment by eerhardt** [comment]
The current behavior is what we want for DependencyModel 2.0 - when running with a 2.0 host, only look in the additional-probing-paths that are passed by the host.

Since the tests now run on the 2.0 host, we've updated the tests to account for this behavior.

Closing.
