### ISSUE TITLE
build.sh should just call run.sh directly

### ISSUE THREAD

**Issue by ellismg** [dotnet/core-setup#2313]
Today build.sh does some parsing and then calls run.sh with a different set of arguments.  This is different from build.cmd which just forwards its arguments to run.cmd.

Because of how this is done, you can't use the -- trick to pass additional properties to MSBuild on *nix.

We should either adopt `run.sh` fully or remove it and go back to parsing in shell scripts.  Landing on run.sh is probably the most expedient thing.

Long term, we need to ensure the native code is still build-able without managed code.

**Comment by chcosta** [comment]
Completely agree. Thanks for filing an issue on this, it's something that I've mentioned in passing to a few people, but never remembered to create an issue for when I'm at my desk. 

My hope is that we move away from run, or at least make it sane , but there is no alternative at the moment. I think I that using run for Unix right now makes the most sense because having two different parsing systems is ridiculous, and the lack of direct control is obnoxious.

**Comment by ellismg** [comment]
> I think I that using run for Unix right now makes the most sense because having two different parsing systems is ridiculous

Okay, this is sort of blocking some things I want to do, so I'll come up with a PR.
