### ISSUE TITLE
Framework packages should use TFM-specific content packages

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2437]
Please see discussion in https://github.com/dotnet/core-setup/pull/2422

**Comment by ericstj** [comment]
When doing this we should see if we can harvest the dependencies from the previous NETCore.App package as well.

**Comment by ericstj** [comment]
NuGet doesn't allow for framework + RID specific dependencies.  You can only have one or the other.  
It's also undesirable to download things (like reference assemblies) that you don't need.  This is especially true when considering our flat framework packages.

This is important for side-by-side behavior for our framework packages.

We want the latest framework package to support all TFMs.
When targeting a specific TFM we only want to download packages relevant to that TFM.

To do this we'll have framework-specific content packages.

Rather than putting the latest reference-content and runtime.json in the identity package for the framework, we'll put it in a framework specific content package.

For NETCoreApp, we'll need to build one of these for 2.0 as well as 2.1 (latest).

For UWP we'll just build one for latest.

**Comment by Petermarcu** [comment]
@weshaggard @ericstj is this still relevant?

**Comment by weshaggard** [comment]
I think we are are moving towards a model of only supporting the latest TFM in the latest package but we have yet to pull the trigger and remove the current support and make it official. Assuming we make it official then we don't do anything for this but we need to think through the different scenarios before we make that call.

**Comment by weshaggard** [comment]
@ericstj thoughts on whether or not we should do this split still or make the package specific to a single TFM?

**Comment by weshaggard** [comment]
I agree lets move forward with the decision to only support the matching TFM from the platform package. Do you think it is worth adding some placeholders for the other platforms or something that will error out if they are tried to be used in the wrong context?

**Comment by weshaggard** [comment]
As part of https://github.com/dotnet/core-setup/issues/4071 I'm going to remove all but the latest TFM from Microsoft.NETCore.App.
