### ISSUE TITLE
Move Core-Setup build definitions from MSENG to VSO

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/core-setup#256]
CoreCLR and CoreFX have their build definitions in VSO - we should do the same from Core-Setup. The pipebuild definition for Core-Setup is already in VSO, so it's just a matter of replicating the existing MSENG definitions in VSO. I actually plan on refactoring those definitions first, as well.

**Comment by eerhardt** [comment]
The reason core-setup's build definitions are on MSENG is because it has special signing requirements (I think it is windows installers that are the problem). In order to sign correctly for core-setup, we are calling the `Microsoft Code Signing` VSO build step, which isn't available on devdiv.visualstudio.com (and the owners of devdiv tenant didn't want to enable it).

So signing will need to be figured out.  This isn't just as simple as "cloning the build defs".

**Comment by gkhanna79** [comment]
CC @weshaggard

**Comment by wtgodbe** [comment]
@naamunds has been working on this

**Comment by naamunds** [comment]
The remaining work is:

- Port  #1148, #1149, #1309, and #1393 to the release/1.0.0 and release/1.1.0 branches (the only change should be setting the defaultBranch in each build definition to the appropriate branch)
- Update the release/1.0.0 and release/1.1.0 pipebuild definitions to use the checked-in build definitions.
- Update the core-setup pipelines.json files in the VSTS repo to say that they're deprecated with a pointer to the checked-in build definitions, as was done for CoreFX.

/cc @dleeapho

**Comment by danmosemsft** [comment]
@ravimeda @dleeapho is this closable now? 
//cc @gkhanna79

**Comment by ravimeda** [comment]
Yes. Sorry for keeping it open.
