### ISSUE TITLE
Remove global location lookup from path in non windows

### ISSUE THREAD

**Issue by ramarag** [dotnet/core-setup#2611]
On linux we infer the global location from the dotnet on the path, 
This needs to change. As a  first step  remove the PATH based current logic at 
https://github.com/dotnet/core-setup/blob/c3dd461c99bfdcb8d136bedf33e46156682fc348/src/corehost/common/pal.unix.cpp#L242
instead return an empty string.

The correct solution is to identify the global location for the various distros, i.e the location where our installers install dotnet:
 
1.	DEB packages:  /usr/share/dotnet
2.	RPM packages: /usr/share/dotnet
3.	PKG for OSX: /usr/local/share/dotnet

cc @eerhardt @gkhanna79 

@steveharter can you bring in the fix ?

**Comment by gkhanna79** [comment]
cc @leecow @Petermarcu since this was discussed in shiproom last Thursday.

**Comment by eerhardt** [comment]
I discussed this last week with a few people that had more Unix knowledge than I do.  The consensus was that if we felt it was necessary to define a "global" location on Unix, we should make it configurable/customizable.  The reason for this is that distros change file system layouts.  And also because end-users may have reasons for wanting to point to other "global" locations - they may not have read/write permissions to what we think is the "global" location, or that disk may be full, or on a network share, etc.

So with that in mind, if we have to define a "global" location on Unix, we should:

1. Not hard-code the default global locations into source code.  Instead provide them through a build-time variable.  This follows the makefile `./configure --prefix=/path/to/dotnet` pattern/usage.
1. Optionally, consider defining an environment variable that will override/augment the default global location. This allows an end-user to point to a custom location, if the default location doesn't work for them and they aren't building from source.
  - We should ensure using an environment variable isn't a security violation before we go through with this approach.  It could cause a privileged `dotnet` host to use a shared framework that is in a non-privileged area on disk, which may lead to an elevation of privilege. 

However, I am still not convinced that user scenario here is valuable enough to support this feature on Unix at all.  We could just completely remove the "global" location concept on Unix until we have a strong need for it.

The only valid use case that I've heard is where someone downloads/installs a dotnet host to a "non-global" location and wants any patch/security updates that are installed through a package manager to the "global" location to automatically roll-forward the shared fx.  However, in this case, I would question why the person didn't just use the `dotnet` that was installed in the "global" location in the first place.  Maybe they needed `2.0` at the time, and didn't have rights to install it to the "global" location.  So they installed it to a different place on the machine.  Now a few months later, an admin installs a `2.0.1` security patch in the "global" location.  Any `2.0` apps running on that machine would automatically start running against `2.0.1`, no matter which host was used to invoke the app.

**Comment by gkhanna79** [comment]
> We could just completely remove the "global" location concept on Unix until we have a strong need for it.

Given that this applies to multi-hive lookup that is for the developer scenarios that were discussed few weeks ago, @davidfowl, what are your thoughts on not supporting the concept of global location on non-Windows?

@eerhardt If we had to give flexibility, I would go with option (1) above since global location is what would map to where our installers would install.

**Comment by eerhardt** [comment]
Note that the numbers above aren't mutually exclusive.  I think our options are:

0. "no global location", 
1. (1) above
2. (2) above
3. (1) above and (2) above
4. Keep existing behavior of reading `$PATH` - not my preferred approach, but listing here for completeness.

**Comment by steveharter** [comment]
Since this is currently a 2.0.0 issue ideally the solution should be baked but extendable later if necessary. So not supporting a global location would be the least risky at this point, assuming it could support the multi-hive developer scenarios.

**Comment by gkhanna79** [comment]
Even if we decide not to support global location, we will need to remove its current implementation based upon PATH (which is (4) above in Eric's response).

**Comment by steveharter** [comment]
I'll have a PR soon with with the current implementation removed. Then we can add if necessary.

**Comment by steveharter** [comment]
Linked the PR that does the removal of the current PATH implementation (as a first step).

**Comment by steveharter** [comment]
Closing for now as changes to disable PATH have been merged. If we decide to add a concept of 'global locations' back for non Windows then I assume that will be a new issue.
