### ISSUE TITLE
.NET CLI segfaults on macOS High Sierra beta

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2649]
_From @wjk on June 6, 2017 17:3_

First of all, I’m sorry if I wasn’t supposed to discuss this issue publicly. I checked the Apple developer program agreement and it seems to allow public discussion of bugs in Apple beta software, provided it has been publicly announced at WWDC (which was yesterday). Also, feel free to move this issue to a more suitable repository if required. (I’m filing it here because I don’t quite know which component this bug is occurring in, due to its intermittent nature.)

## Steps to reproduce

1. Install macOS High Sierra Beta (I’m using build 17A264c).
2. Install .NET Core 1.0.4 (I’m using 1.0.4 instead of 2.0 previews to workaround OmniSharp/omnisharp-vscode#1495).
3. Go to an empty directory and run `dotnet new console`.

## Expected behavior

The command completes successfully.

## Actual behavior

`dotnet` segfaults inside of low-level threading and synchronization code in CoreCLR. ([Here is the full crash log.](https://gist.github.com/wjk/cf1d40c0b123fd90a2e29aae17351bc9)) However, it only seems to do this once it has completed running, as all expected outputs are present on the disk.

In addition, this is an intermittent problem; .NET CLI tasks (such as `dotnet build` or `dotnet restore`) crash, while running a DLL directly using `dotnet exec` seems to work fine.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```

_Copied from original issue: dotnet/cli#6772_

**Comment by livarcocc** [comment]
_From @wjk on June 7, 2017 18:24_

Unfortunately, my note above about the segfault occurring only as the process is exiting has been proven quite false; `dotnet restore` fails to do anything now, because it segfaults immediately upon launch.

**Comment by eerhardt** [comment]
@bartonjs

The crash appears to happen in libcrypto.35.dylib according to the above log.

I would guess .net Core 1.0 isn't going to be supported on newer macOS versions, if Apple can make breaking changes to OpelSSL.

The good news is that from 2.0 forward, we aren't using libcrypto anymore.

**Comment by wjk** [comment]
@eerhardt I have confirmed that this no longer occurs when using 2.0-preview builds of .NET Core.

**Comment by bartonjs** [comment]
libssl.35.dylib is LibreSSL (not OpenSSL).  I'm surprised that libcurl.4.dylib on High Sierra is using LibreSSL... On Normal Sierra (10.12) it's backed by Security.framework / SecureTransport (libcurl's darwinssl engine), rather than libssl (either OpenSSL or LibreSSL).  Seems weird that Apple would change something to prefer a library that they didn't write.

Anyways, the situation we ended up in is that we have two different versions of libcrypto loaded (in this case LibreSSL ("35") and OpenSSL ("1.0.0") and we sent a pointer from one to the other:

> 5   libcrypto.35.dylib            	0x00007fffa4afec23 X509_STORE_CTX_get1_issuer + 227
6   libcrypto.1.0.0.dylib         	0x00000001040e3edb X509_verify_cert + 970
7   ???                           	0x000000010fd22f85 0 + 4560400261
8   ???                           	0x0000000110913ddc 0 + 4572921308
9   ???                           	0x000000010fd1fbfe 0 + 4560387070
10  libcoreclr.dylib              	0x00000001011198b7 UMThunkStub + 273
11  libssl.35.dylib               	0x00007fffa5e642a7 ssl_verify_cert_chain + 471
12  libssl.35.dylib               	0x00007fffa5e4e43f ssl3_get_server_certificate + 911
13  libssl.35.dylib               	0x00007fffa5e4c9cd ssl3_connect + 1485
14  libssl.35.dylib               	0x00007fffa5e6a8b6 SSL_connect + 54
15  libcurl.4.dylib               	0x00007fffa4dab3f3 ossl_connect_common + 321
16  libcurl.4.dylib               	0x00007fffa4daf1b7 Curl_ssl_connect_nonblocking + 77
17  libcurl.4.dylib               	0x00007fffa4d73d1b https_connecting + 23
18  libcurl.4.dylib               	0x00007fffa4d95d76 multi_runsingle + 1012
19  libcurl.4.dylib               	0x00007fffa4d95888 curl_multi_perform + 114
20 System.Net.Http.Native.dylib 0x0000000103683bd1 0x103682000 + 7121

A couple of different fixes have gone in for this for 2.0 (better guarding against talking to two different versions via curl, and some different structural changes to handle/expect using darwinssl on macOS).  As @eerhardt said, I don't expect that we'll takes fixes to 1.x to make it work on High Sierra.

@leecow  / @richlander: Are we anticipating needing to service 1.0 for the new macOS? Or if 2.0 already works is that good enough?

**Comment by Petermarcu** [comment]
We will likely wan to service 1.X to address.

**Comment by leecow** [comment]
Yes, we'll need to address this in 1.x.

**Comment by gkhanna79** [comment]
CC @janvorli

**Comment by bartonjs** [comment]
Fixed by https://github.com/dotnet/corefx/pull/21069 and https://github.com/dotnet/corefx/pull/21071
