### ISSUE TITLE
VS F5 Failure When Referencing pre-release Microsoft.NETCore.UniversalWindowsPlatform with TFM UAP10.0

### ISSUE THREAD

**Issue by zamont** [dotnet/core-setup#2719]
## Steps to reproduce
1. Create new C# Blank App (Universal Windows)
2. Update Microsoft.NETCore.UniversalWindowsPlatform to latest pre-release (6.0.0-preview1-*)
3. Build in Debug configuration

## Expected  behavior
Build succeeds.

## Actual behavior
Build fails. Error message is

```
Payload contains two or more files with the same destination path 'clrcompression.dll'. Source files: 
C:\Users\zamont\.nuget\packages\runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform\6.0.0-preview1-25419-02\runtimes\win10-x86\native\clrcompression.dll
C:\Users\zamont\.nuget\packages\runtime.win7-x86.runtime.native.System.IO.Compression\4.0.1\runtimes\win7-x86\native\clrcompression.dll
```

## Assessment
In the latest metapackage, we have RID-specific packages, as indicated by package runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform. clrcompression.dll is a native binary, so the runtime.win10-x86 package includes clrcompression.dll in the output unconditionally.

**Comment by zamont** [comment]
@joperezr Any ideas how to resolve this issue? I feel like this is a situation we would like to support: user upgrading to our latest metapackage but still remaining on uap10.0 / .NETCore5.0 framework.

**Comment by joperezr** [comment]
Agreed. Do you happen to know who is bringing `runtime.native.System.IO.Compression` do you have your project.assets.json

**Comment by zamont** [comment]
The dependency graph seems to be Microsoft.NETCore v5.0.2 -> System.IO.Compression v4.1.1 -> runtime.native.System.IO.Compression v4.1.0.

I think the problem stems from us including clrcompression.dll in the RID-specific UWP metapackage.

**Comment by joperezr** [comment]
Why are we pulling in the Microsoft.NETCore dependency? that one is not needed any longer as that is now packaged in the metapackage. The reason why clrcompression.dll is present in the metapackage is because it is not packaged individually any longer, so the runtime.native.System.IO.Compression package is not generated any longer, which is why we should instead remove the other references which are trying to pull it in.

**Comment by joperezr** [comment]
cc: @ericstj who is an expert on the area of conflict resolution.

**Comment by zamont** [comment]
Here's a link to the latest UWP metapackage on MyGet: https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.UniversalWindowsPlatform

The Microsoft.NETCore dependency is not brought in for uap10.1 if that's what you're concerned about. We're still talking about the uap10.0 / .NETCore 5.0 case.

**Comment by joperezr** [comment]
Ohh I see I understand the problem now and I think that I know how to fix it. I'll assign this issue to myself.

**Comment by ericstj** [comment]
This isn't a conflict resolution problem.  It's a package authoring problem.

In this case the RID-specific runtime packages for uap10.1 are being brought into the uap10.0 application. Because these packages have native assets in them that aren't TFM specific they are applying to the uap10.0 app.

I think we should do the work to move the runtime.json into a framework specific package, as I was discussing here for netcoreapp: https://github.com/dotnet/core-setup/issues/2437

**Comment by ericstj** [comment]
A quick fix is to put the native stuff under a `runtimes/{rid}/nativeassets/{tfm}` instead of `runtimes/{rid}/native`, but this still causes the packages to be downloaded on the old TFMs.  We need to put the latest stuff in a framework specific package.
