### ISSUE TITLE
Add Tizen Builds to Daily Builds list

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/core-setup#2806]
The output for Tizen is normally built and released.
So we want to add the latest NETCore.App tarball archive to the Daily Builds list in README.md.

/cc @gkhanna79 @hqueue @hseok-oh @seanshpark @ragmani

**Comment by Petermarcu** [comment]
I'm not 100% up to date with how Tizen is building but if you want to submit a PR with the updated to the table with all the right links, we can look at taking it. Is there info you need from the Microsoft team to get the right links?

**Comment by gkhanna79** [comment]
@jyoungyun I believe @weshaggard and @Petermarcu are in the process of enabling the servicing mode for release/2.0.0 branches and can help coordinate that effort.

> I am going to take maternity leave from August 21st. 

Congratulations :)

**Comment by weshaggard** [comment]
@hqueue @hseok-oh @ragmani is this something you guys still want to add to the readme?

**Comment by hqueue** [comment]
@weshaggard Sorry to late to this issue. Right, we are interested in this job.

@alpencolt What do you think of it ? Before we were planning to post our daily build binary to here.

**Comment by alpencolt** [comment]
@hqueue it would be good. But I don't understand what should we do for it.

I can add links to places where we publish packages (http://nuget.org, https://tizen.myget.org and http://download.tizen.org/) into `README.md` but all links in this document refer to  https://dotnetcli.blob.core.windows.net/.
@weshaggard  @Petermarcu could you help us?

cc @gbalykov @Dmitri-Botcharnikov

**Comment by hqueue** [comment]
> @hqueue it would be good. But I don't understand what should we do for it.
> I can add links to places where we publish packages (http://nuget.org, https://tizen.myget.org and http://download.tizen.org/) into README.md

I don't think we have a tarball at http://nuget.org, https://tizen.myget.org and http://download.tizen.org.

There are tarballs for  `Linux (armhf) (for glibc based OS)` at https://github.com/dotnet/core-setup#daily-builds and this issue was opened to add  a tarball for `Tizen (armel)`, for example, at
https://github.com/dotnet/core-setup#daily-builds.
@alpencolt So it would be great to publish a tarball instead of `nupkg` or `rpm`.  What do you think of it? AFAIK we already produces tarball from Jenkins. So we can make use of a static link for our Jenkins daily build to publish tarball of upstream `master` and `2.0.x` to here,  

> but all links in this document refer to https://dotnetcli.blob.core.windows.net/.
And I hope @weshaggard can help us.

@weshaggard Can you help us out ?

**Comment by weshaggard** [comment]
>@weshaggard Can you help us out ?

**Comment by jyoungyun** [comment]
This issue is outdated. I will close it.
