### ISSUE TITLE
Lack of description for the dotnet.exe

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2817]
_From @Rovastar on July 12, 2017 16:25_

not sure where to post this so posting in multiple locations.

Can we have a description for the dotnet.exe (for Windows)?
Currently it just shows up in Task Manger when running with no description and just displaying the exe name "dotnet"
A more meaningful description would be useful mentioning that this is the Core version and probably the version number in there.
".NET Core runtime" or something.

_Copied from original issue: dotnet/cli#7134_

**Comment by rakeshsinghranchi** [comment]
@leecow  , PTAL and suggest the description text.

**Comment by steveharter** [comment]
Note in task manager you can now add the column for the Command Line which greatly helps.

Also Task Manager has been extended by the Edge browser to list each tab; there have been discussions to extend this into a general mechanism for others to use but that is not ready yet. That would enable us to show additional information (the name of the app for example) directly.

**Comment by steveharter** [comment]
@leecow are you planning anything for 2.1.0? If not, please move to future or 2.2.0. Thaks

**Comment by leecow** [comment]
".NET Core Runtime - [version]" seems useful. 

cc @richlander @KathleenDollard

**Comment by rakeshsinghranchi** [comment]
@steveharter , Looks like https://github.com/dotnet/core-setup/issues/2007 has more details. This is pertaining to dotnet.exe payload and not the setup. Shall I assign this bug to you?

**Comment by steveharter** [comment]
I think this issue is for the actual dotnet.exe "File Description" for Windows (right-click on dotnet.exe, properties, details). This would be the same for all dotnext.exe for a given release, so probably not that useful to distinguish from multiple apps. So I'm assuming this would be an area-Setup feature?

The issue https://github.com/dotnet/core-setup/issues/2007 would be a longer-term task manager extensions or named exe, and it's assigned to area-Host already.
