### ISSUE TITLE
Transition Core-Setup build to MSBuild/BuildTools

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#283]
CC @schellap

**Comment by dagood** [comment]
Just to explicitly link the issues together, this is required for https://github.com/dotnet/core-setup/issues/253 (better auto-PR), https://github.com/dotnet/core-setup/issues/238 (automatically create new metapackages), and https://github.com/dotnet/core-setup/issues/259 (multiple builds per commit).

**Comment by gkhanna79** [comment]
Assigning to @AlfredoMS who is working on this for build-from-source.

**Comment by AlfredoMS** [comment]
My dev branch: My dev branch: https://github.com/AlfredoMS/core-setup/tree/buildtools

Work so far:
- Product build is almost complete. I still need to add crossgening

To be done:
- Packaging
- Publishing

Also I need to rebase to include the changes made by @schellap on https://github.com/dotnet/core-setup/pull/711

**Comment by dagood** [comment]
@AlfredoMS Do you plan on maintaining the current CLI-style publishing logic, or changing to the way corefx/coreclr/wcf do it?

**Comment by gkhanna79** [comment]
CC @wtgodbe @ramarag

**Comment by AlfredoMS** [comment]
@gkhanna79 the idea is to replace all the CLI style with buildtools 

cc @ellismg

**Comment by AlfredoMS** [comment]
I haven't started the work on publishing, but if there are any particular concerns please let me know soon.

**Comment by AlfredoMS** [comment]
Update:

New dev branch: https://github.com/AlfredoMS/core-setup/tree/build-eng 

I expect this to build and package on all OS in the next couple of days. After that I will work on the publishing step.

**Comment by AlfredoMS** [comment]
New public branch https://github.com/dotnet/core-setup/tree/buildtools
Work to be completed on this branch before merging into master.

@ellismg

**Comment by AlfredoMS** [comment]
**How to use new branch**

Windows:
- run build.cmd
Mac and Linux
- run build.sh -- /p:TargetRid= [your desired target rid, e.g. osx.10.10-x64  or ubuntu.16.04-x64

you can use -verbose for msbuild verbose logging and -SkipTests=true to skip test that are broken*

To run the build step by step you can use this commands just add .sh or .cmd according to your os

sync
run build-custom -verbose -- src/corehost/build.proj
run build-custom -verbose -- build/tasks/core-setup.tasks.builds
run build-custom -verbose -- pkg/dir.proj
run build-custom -verbose -- src/dir.proj
run build-custom -verbose -- test/dir.proj
run build-custom -verbose -- packaging/dir.proj

for mac and linux specify the os and TargetRid
example:
run build-custom -verbose -OSGroup=OSX -- src/corehost/build.proj /p:TargetRid=osx.10.10-x64
run build-custom -verbose -OSGroup=Linux -- src/corehost/build.proj /p:TargetRid=ubuntu.16.04-x64


If you are planning on making new changes you should get familiar with the new build and bin structure.
Known issues:
- Publishing is not ready
- Tests are broken. I have a workaround but it still depends on the old build system. Use flag "-SkipTest=true"
- Build.sh needs improvements to generated targetrid or accept one as parameter
- checked in build definitions for jenkins and vsts have not been updated
- upgrade version tool has not been updated.
- generated packages will have the version suffix 0009999, this is intentional to help identify built binaries while testing the branch, will be changed for the final version.

**Comment by chcosta** [comment]
All of the "known issues" have been fixed except that the checked in build definitions are still being updated.  Other active issues (marked with label "[area-CoreSetup-on-BuildTools](https://github.com/dotnet/core-setup/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-CoreSetup-on-BuildTools)") are being used to track additional work.  Closing this issue.
