### ISSUE TITLE
runtime args error giving a bad message

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2898]
_From @janvorli on July 24, 2017 22:51_

@pynixwang commented on [Sun Jun 25 2017](https://github.com/dotnet/coreclr/issues/12446)

```Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
         http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

when i use dotnet runtime but dll path is error,  `dotnet` show me this bad message, it 's very hard to find the problem. other errors also show this message.

_Copied from original issue: dotnet/cli#7249_

**Comment by steveharter** [comment]
Similar to https://github.com/dotnet/core-setup/issues/2845 which I'm working on

**Comment by steveharter** [comment]
I am not sure from the original text ("when i use dotnet runtime but dll path is error") what the actual repro was. Assuming it was because the specified framework was not found, I'm closing this issue since that error message was significantly improved already to list the available frameworks and how to install just the runtime.

Besides the missing framework case, that fwlink shown can appear in two other cases:
1) The load_library of the specified dll fails, likely because of a missing dependency
2) An SDK command was given, but the SDK is not installed

And both have an acceptable error message:
1) "`The library %s was found, but loading it from %s failed. Installing .NET Core prerequisites might help resolve this problem."
2) "Did you mean to run dotnet SDK commands? Please install dotnet SDK from:  %s"
