### ISSUE TITLE
Don't assume dotnet.exe is the only host

### ISSUE THREAD

**Issue by davidfowl** [dotnet/core-setup#2983]
It seems that the logic in hostfxr.dll assumes dotnet.exe is the process that is activating it. I'm trying to launch the .NET Core host from a native IIS module and I can't exactly replicate the lookup behavior because it assumes the initial search path is the executing process instead of the hive where hostfxr.dll is loaded from:

```
--- Invoked hostfxr [commit hash: 40c565230930ead58a50719c0ec799df77bddee9] main
Own dll path 'C:\Program Files\IIS Express\iisexpress.dll'
Checking if CoreCLR path exists=[C:\Program Files\IIS Express\coreclr.dll]
--- Executing in muxer mode...
Detected a non-standalone application, expecting app.dll to execute.
Treating application 'C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.dll' as a managed executable.
App runtimeconfig.json from [C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.dll]
Runtime config is cfg=C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.runtimeconfig.json dev=C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.runtimeconfig.dev.json
Attempting to read runtime config: C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.runtimeconfig.json
Attempting to read dev runtime config: C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.runtimeconfig.dev.json
Runtime config [C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.runtimeconfig.json] is valid=[1]
Ignoring host interpreted additional probing path C:\Users\dfowler\.dotnet\store\x64\netcoreapp2.0 as it does not exist.
--- Resolving FX directory, specified ''
Searching FX directory in [C:\Program Files\IIS Express\]
Attempting FX roll forward starting from [2.0.0]
Applying patch roll forward from [2.0.0]
Searching FX directory in [C:\Program Files\dotnet]
Attempting FX roll forward starting from [2.0.0]
Applying patch roll forward from [2.0.0]
Inspecting version... [1.0.5]
Inspecting version... [1.1.2]
Inspecting version... [2.0.0-preview1-002111-00]
Inspecting version... [2.0.0-preview2-25407-01]
It was not possible to find any compatible framework version
Executing as a portable app as per config file [C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\SampleServer.runtimeconfig.json]
--- Resolving hostpolicy.dll version from deps json [Microsoft.NETCore.App.deps.json]
Dependency manifest [Microsoft.NETCore.App.deps.json] does not exist
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0.0'.
```

Versus running from the command line:

```
--- Invoked hostfxr [commit hash: e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d] main
Own dll path 'C:\Users\dfowler\.dotnet\x64\dotnet.dll'
Checking if CoreCLR path exists=[C:\Users\dfowler\.dotnet\x64\coreclr.dll]
--- Executing in muxer mode...
Detected a non-standalone application, expecting app.dll to execute.
Treating application 'C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\
mpleServer.dll' as a managed executable.
App runtimeconfig.json from [C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcore
p2.0\SampleServer.dll]
Runtime config is cfg=C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\
mpleServer.runtimeconfig.json dev=C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\ne
oreapp2.0\SampleServer.runtimeconfig.dev.json
Attempting to read runtime config: C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\n
coreapp2.0\SampleServer.runtimeconfig.json
Attempting to read dev runtime config: C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Deb
\netcoreapp2.0\SampleServer.runtimeconfig.dev.json
Runtime config [C:\Users\dfowler\Documents\GitHub\AspNetCoreModule\samples\SampleServer\bin\Debug\netcoreapp2.0\Sample
rver.runtimeconfig.json] is valid=[1]
Ignoring host interpreted additional probing path C:\Users\dfowler\.dotnet\store\x64\netcoreapp2.0 as it does not exis

--- Resolving FX directory, specified ''
Searching FX directory in [C:\Users\dfowler\.dotnet\x64\]
Attempting FX roll forward starting from [2.0.0]
Applying patch roll forward from [2.0.0]
Inspecting version... [1.0.5]
Inspecting version... [1.1.2]
Inspecting version... [2.0.0]
Inspecting version... [2.0.0-preview2-25407-01]
Inspecting version... [2.0.0-preview3-25413-01]
Inspecting version... [2.0.0-preview3-25426-01]
Inspecting version... [2.0.0-preview3-25427-02]
Inspecting version... [2.0.0-preview3-25428-01]
Inspecting version... [2.0.0-preview3-25502-01]
Inspecting version... [2.0.0-preview3-25510-01]
Inspecting version... [2.0.0-preview3-25516-01]
Inspecting version... [2.0.0-preview3-25518-01]
Attempting FX roll forward starting from [2.0.0]
Applying patch roll forward from [2.0.0]
Inspecting version... [2.0.0]
Inspecting version... [-1.-1.-1]
Changing Selected FX version from [] to [C:\Users\dfowler\.dotnet\x64\shared\Microsoft.NETCore.App\2.0.0]
Searching FX directory in [C:\Program Files\dotnet]
Attempting FX roll forward starting from [2.0.0]
Applying patch roll forward from [2.0.0]
Inspecting version... [1.0.5]
Inspecting version... [1.1.2]
Inspecting version... [2.0.0-preview1-002111-00]
Inspecting version... [2.0.0-preview2-25407-01]
Chose FX version [C:\Users\dfowler\.dotnet\x64\shared\Microsoft.NETCore.App\2.0.0]
```

/cc @nguerrera @steveharter

**Comment by steveharter** [comment]
This behavior is by design, so marking this issue as an enhancement.

What is the expected timeframe of new behavior around this?

In order to use hostfxr.dll location, we would need to discuss options. Currently hostfxr is located in a folder like this: ```dotnet/host/fxr/<hostversion/``` so we would need to back up a couple directories to find the shared locations ```dotnet/shared/Microsoft.NETCore.App/<sharedversion>```. That doesn't seem ideal.

There are other options we could use; some thinking along these lines is at the end of https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md

**Comment by davidfowl** [comment]
@steveharter We need this for 2.1.

/cc Managers: @muratg @Petermarcu 
/cc @jkotalik

**Comment by davidfowl** [comment]
@steveharter Ideally you would use the module directory of the `hostfxr.dll` not the host process that loads `hostfxr.dll`

**Comment by jkotalik** [comment]
Any updates on this issue? It is required for a 2.1 feature of ours to work.

**Comment by steveharter** [comment]
I haven't started the implementation, but it is marked for 2.1. If it is blocking, I can bump it up.

Is the work to create dotnet.dll (instead of dotnet.exe) required as well? Or is the ask just to also look for the runtime and sdk in a relative subdirectory from the `hostfxr.dll` directory?

**Comment by nguerrera** [comment]
What is this talk of another dotnet.dll? dotnet.dll is the name of the sdk implementation assembly, that could get confusing and cause problems.

**Comment by muratg** [comment]
The feature we're working on is launching the host from an IIS module to run the user's app behind IIS. SDK/runtime won't be under that folder at all.  w32p is the process that loads the host.

dotnet.dll is not related to this issue at all.

**Comment by steveharter** [comment]
I saw dotnet.dll in a path above; I was assuming that was the native code that loads hostfxr.dll

**Comment by Petermarcu** [comment]
>> Or is the ask just to also look for the runtime and sdk in a relative subdirectory from the hostfxr.dll directory?

I'm assuming its just this. @muratg @davidfowl @jkotalik can you confirm?

**Comment by muratg** [comment]
Yes, I think that's the fix.  From @davidfowl's logs above, When we're loading the host from our IIS module (instead of running dotnet.exe), we're getting:

```
--- Resolving FX directory, specified ''
Searching FX directory in [C:\Program Files\IIS Express\]
```

Instead of:

```
--- Resolving FX directory, specified ''
Searching FX directory in [C:\Users\dfowler\.dotnet\x64\]
```

**Comment by muratg** [comment]
Re: priority of this: I'm not sure how risky/big of a change this is (I assume not very?), but can we do this earlier?  We have the feature mostly implemented on our side and ideally we'd like to release it in the first possible preview.

**Comment by steveharter** [comment]
Where will the hostfxr.dll will exist, and how is that file is placed there? I assume it is not in the standard `<dotnet.exe location>\host\fxr\<version>\` directory. Is this a potential problem since that is currently a versioned file? It is versioned because semantics can change between releases...

**Comment by steveharter** [comment]
Some implementation options to trigger the new functionality:
1)	Add an argument; something like `--hostfxrLocation <location>`
•	Specify in `<app>.runtimeconfig.json` and\or in the current hostfxr_main(argv) entry point.
2)	Dynamically get the current module directory (of hostfxr.dll) and use that.
•	I know how to do this in Windows, but I don't believe there is a good way to do this in Unix\Mac (I can research if we decide this is a worthy option).
•	I assume the preferred ordering is to use the current module directory first, and then the shared location.
•	I would like to prevent this functionality for the normal dotnet.exe scenario (for risk).
3)	Use hostfxr_main(argv[0]) to specify the path to hostfxr.dll (IIS module would have to pass this)
•	Normally argv[0] is the location of the current exe, but is somewhat platform-defined.
•	argv[0] is not used today in hostfxr.dll, so using it for this new functionality won't break anything. It would only be used if hostfxr is the actual file name, meaning we still use the current exe directory for dotnet.exe and don't rely on argv[0] for that.

**Comment by muratg** [comment]
@steveharter We're not changing where hostfxr.dll is.  It's the standard location where the installers lay it down.

In our case, it gets activated by a different exe (w3wp in `C:\Program Files\IIS Express\`) instead of dotnet.exe in it's standard location.

**Comment by steveharter** [comment]
@muratg ok good on using hostfxr.dll in its current location. So for the options 1 and 3 mentioned above, the directory specified should be to the 'root' location (where dotnet.exe is located) and not the hostfxr.dll location. Otherwise, if we use the hostfxr.dll location we would go up two directories to find the 'root' which is a bit odd, but that is what we would need to do for option 2.

**Comment by muratg** [comment]
@davidfowl @jkotalik What's our preference on that?

**Comment by jkotalik** [comment]
I'm fine with either option 1 or 3. Note that our use case is only for Windows, but this behavior should be cross platform.

**Comment by steveharter** [comment]
Here's more detail on option 3:

The method `hostfxr_main` in hostfxr.dll is the entry point that is called by dotnet.exe and I assume the IIS hosting module. Like other `main` methods in C\C++ it has the following signature to allow arguments to be passed:
```c
(const int argc, const pal::char_t* argv[])
```

As part of the C standard, argv[0] "represents" the program name, which is normally the full path to the executable, but can be null or something else that "represents" the program name. So it is not a stretch to use this to represent the full path to the root of the shared location (where the shared dotnet.exe is located), even if another .exe is hosting or serving as a surrogate to dotnet.exe.

Since argv[0] is a full path it includes a filename, so "dotnet.exe" should be appended, although the actual file name is not required since hostfxr.dll will only take the path portion.

Note that today hostfxr.dll requires argv[0], but it is ignored and the directory of the current process is used instead. To have a consistent approach going forward, we could change that logic to always use argv[0], pending testing to ensure that the full path is always specified including cases where we have a standalone exe named <mayapp.exe>.

**Comment by jkotalik** [comment]
@steveharter that sounds good. I believe it should work in our scenario. As long as we can call "hostfxrmain PATH_TO_DLL", we should be able to consume it. @davidfowl just want to confirm with you before we add this functionality.

**Comment by steveharter** [comment]
I assume we are favoring option 3, using argv[0] to specify the root path. That is simpler than option 1 anyway, and option 2 may have some cross-plat issues \ higher cost.

@jkotalik you would call hostfxrmain with the same arguments you use today (I assume something like argv[1]="exec" and argv[2]=<path to dll>) except argv[0] would be the root path (e.g. `C:\program files\dotnet\dotnet.exe` or perhaps just `C:\program files\dotnet\`). Since you already loaded hostfxr.dll somehow, you would back up three directories from where that is located (e.g. `C:\program files\dotnet\host\fxr\<version>`), possibly append `dotnet.exe`, and pass that as argv[0].

@davidfowl if just a path and no filename is passed (e.g. "dotnet.exe"), that should work provided it ends with a slash to disambiguate the directory name from a file. I'll need to test this out though.

**Comment by steveharter** [comment]
Note the current code in the PR requires a filename, so `dotnet.exe` should be appended to the path.
