### ISSUE TITLE
[Arm64/Unix] Need instructions to build core-setup for new RID/arm64-linux

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/core-setup#3092]
Need to add new arm64 Linux platform support.  

Currently corefx and coreclr have RID and nuget pkgs.  Packages are not yet be published to Myget, so it is difficult to build test core-setup for arm64.

@janvorli I heard you were preparing documentation.  
@RussKeldorph FYI

**Comment by janvorli** [comment]
@sdmaclea if you already have packages for corefx and coreclr, then do the following steps.
First, create a new folder called e.g. combinednugets and then copy the nuget packages built in corefx and coreclr repo into this folder like this (assuming you are building a release version):
```sh
cp -r /path/to/coreclr/bin/Product/Linux.x64.Release/.nuget/pkg/* /path/to/combinednugets/
cp -r /path/to/corefx/bin/packages/Release/* /path/to/combinednugets/
```
Now in the core-setup repo, run:
```sh
./build.sh -release -DistroRid=linux-arm64 -os=Linux -- /p:OverridePackageSource=/path/to/combinednugets/
```
That should produce the core-setup packages and also run a core-setup test suite.

**Comment by janvorli** [comment]
@sdmaclea  actually, I've forgotten to mention one thing. You'll also need to modify the dependencies.props in core-setup root folder. The CoreFxVersion element needs to have the version of the packages built in corefx, the MicrosoftNETCoreRuntimeCoreCLRPackageVersion the version of packages built in coreclr. Without that, the core-setup won't be able to pick them.

**Comment by sdmaclea** [comment]
@janvorli  Thanks I'll give it a try.  

If you are writing formal docs, as suggested elsewhere...
> `cp -r /path/to/coreclr/bin/Product/Linux.x64.Release/.nuget/pkg/* /path/to/combinednugets/`

should probably be
`cp -r /path/to/coreclr/bin/Product/Linux.arm64.Release/.nuget/pkg/* /path/to/combinednugets/`

**Comment by janvorli** [comment]
Oh, I am  sorry for forgetting to update the architecture for your case.

**Comment by sdmaclea** [comment]
@janvorli Looks like the instructions are incomplete it seems to be building x64 binaries.

I suspect I need to add ` -TargetArchitecture=arm64` to the build.sh command. 

Some of the following might also want to be set
+ `-PortableBuild`
+ `-CrossBuild`
+ `-DisableCrossgen`

**Comment by sdmaclea** [comment]
I was able to cross build like this
```
export ROOTFS_DIR=<rootfs_path>
./build.sh -release -DistroRid=linux-arm64 -os=Linux -TargetArchitecture=arm64 -CrossBuild=true -DisableCrossgen=true -SkipTests=true -- /p:OverridePackageSource=<pkg_path>
```

**Comment by sdmaclea** [comment]
Native build is not yet supported as the dotnet cli tools are not available

**Comment by janvorli** [comment]
Great, I have not realized you were cross building the stuff and I have thought we already have a bootstrap dotnet cli.

**Comment by sdmaclea** [comment]
@janvorli Do you have any hints on creating the arm64 [bootstrap] CLI?  Should we open an issue in core/cli?

**Comment by sdmaclea** [comment]
@janvorli BTW thanks.

**Comment by janvorli** [comment]
@sdmaclea I am just learning about how the full CLI is built. Building the bootstrap CLI is quite straightforward, I have a shell script that does that end to end that I am going to publish. But there are some tricky parts. The way the bootstrap cli is created is that we take an existing cli for another platform (call it a seed cli) and replace the native components with native components built for the target platform. Since the managed and native components must match, the native components must be built from the coreclr, corefx and core-setup trees at the same commit the ones in the seed cli were built from (this could be a bit relaxed - you could take a newer versions if there were no changes in the managed to native interfaces like the corefx shims and System.Private.CoreLib.dll to libcoreclr.so). That can be a problem if you need some changes that are newer than those commits. I have usually solved it by cherry picking some changes from the tip and back porting them to the sources checked out at the needed commit and building System.Private.CoreLib.dll on a supported system from the same sources.
And there is one more issue here - the fact ARM64 is a different architecture. The publicly available CLI contains assemblies that are already crossgen-ed, so probably the easiest way is to build CLI yourself for a x64 supported platform with crossgenning turned off and use that as the seed cli.

**Comment by sdmaclea** [comment]
@janvorli It sounds a lot like how I build and run asp.net benchmarks.  Sounds like I can just use the version specified by dependencies.prop.  I'll look at building CLI for x64 w/o crossgen.  I look forward to your scripts.
