### ISSUE TITLE
on gentoo ,run  dotnet new console  ,generate err : Cannot get required symbol ECDSA_sign from libssl

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3190]
_From @availa on September 12, 2017 2:9_

## Steps to reproduce
install gentoo x86_64 
install .net core 2.0 x64 linux sdk,
run dotnet new console

## Expected  behavior
new project created

## Actual behavior
dotnet new console

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Cannot get required symbol ECDSA_sign from libssl
Aborted (core dumped)

## Environment data

(1) gentoo  kernel 4.13.0 x86_64

(2) openssl  1.0.2l

(3) curl 
curl --version
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy 

(4) `dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     gentoo
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/availa/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

_Copied from original issue: dotnet/cli#7633_

**Comment by livarcocc** [comment]
@steveharter can you take a first look? If this is an issue with dotnet new, please, move this bug to dotnet/templating.

**Comment by availa** [comment]
today ,i have downloaded the latest daily build sdk ,
also the same result:

~/Downloads/dotnet-sdk-latest-linux-x64 $ ./dotnet new console

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

Configuring...
--------------
A command is running to populate your local package cache to improve restore speed and enable offline access. This command takes up to one minute to complete and only runs once.
Decompressing 100% 8101 ms
Expanding 100% 19312 ms
Cannot get required symbol ECDSA_sign from libssl
Aborted (core dumped)


===================

./dotnet --info
.NET Command Line Tools (2.1.0-preview1-007191)

Product Information:
 Version:            2.1.0-preview1-007191
 Commit SHA-1 hash:  6fdc98c23b

Runtime Environment:
 OS Name:     gentoo
 OS Version:  
 OS Platform: Linux
 RID:         gentoo-x64
 Base Path:   /home/availa/Downloads/dotnet-sdk-latest-linux-x64/sdk/2.1.0-preview1-007191/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25616-02
  Build    : 8aa34a95bad481e1b5e4c8286e5cb2d7cb6ed943

**Comment by steveharter** [comment]
I can repro the issue that returns `Cannot get required symbol ECDSA_sign from libssl`

It appears that symbol is not present in libssl.so. I verified by looking at the exports in the lib64/libssl.so file.

Doing an `openssl` and then `version` command yields 1.0.2h which is new enough to have the ECDSA (Elliptic Curve cryptography) support, so it appears that gentoo has disabled ECDSA.

You may have luck building OpenSsl locally, although checking with gentoo first would be a good idea.

cc @bartonjs

**Comment by bartonjs** [comment]
It seems weird that we're looking for ECDSA_sign from libssl; I'd expect it from libcrypto.

```sh
$ objdump -T /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 | grep ECDSA_sign
0000000000105780 g    DF .text  0000000000000085  OPENSSL_1.0.0 ECDSA_sign_ex
0000000000105830 g    DF .text  000000000000004d  OPENSSL_1.0.0 ECDSA_sign_setup
0000000000105810 g    DF .text  0000000000000015  OPENSSL_1.0.0 ECDSA_sign
$ objdump -T /lib/x86_64-linux-gnu/libssl.so.1.0.0 | grep ECDSA_sign
0000000000000000      DF *UND*  0000000000000000  OPENSSL_1.0.0 ECDSA_sign
```

**Comment by steveharter** [comment]
Yes ECDSA_sign is in both libssl and libcrypto for me as well (on Ubuntu). Since we link against both, it probably just uses the first one it finds.

On Gentoo, there are no ECDSA exports in either library except for a handful of ENGINE_*_ECDSA methods in librypto, such as `ENGINE_get_ECDSA`.

**Comment by bartonjs** [comment]
If my ebuild-ese is functioning correctly Gentoo disables ECC because of "maybe there's a patent problem" reasons (https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/openssl/openssl-1.0.2l.ebuild) if `bindist` is set.

https://packages.gentoo.org/useflags/bindist confirms this:


Package | “bindist” Flag Description
-- | --
dev-libs/openssl | Disable EC algorithms (as they seem to be patented) -- note: changes the ABI


So it seems like the answer is to clear bindist, or contextually clear it for openssl, and re-emerge openssl.

**Comment by steveharter** [comment]
Success!

I didn't make any changes with the bindist (binary distribution) flag, but did run these:
```
emerge --unmerge openssl
emerge openssl
```

However the first time I tried to run `emerge openssl` it failed; timeouts trying to download `openssl-1.0.2h.tar.gz`

**Comment by steveharter** [comment]
Closing this as it was an issue with gentoo distribution of OpenSsl.

@availa and others please report back on what worked or didn't. Thanks

**Comment by availa** [comment]
as you say ,
i have successed,by  this steps 

`
1. emerge --unmerge openssl
2. USE="-bindist" emerge openssl
`

then 

`$ dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/availa/src/dotnet/dotnet.csproj...
  Restoring packages for /home/availa/src/dotnet/dotnet.csproj...
  Generating MSBuild file /home/availa/src/dotnet/obj/dotnet.csproj.nuget.g.props.
  Generating MSBuild file /home/availa/src/dotnet/obj/dotnet.csproj.nuget.g.targets.
  Restore completed in 198.65 ms for /home/availa/src/dotnet/dotnet.csproj.


Restore succeeded.
`


thanks  to all  @livarcocc   @steveharter  @bartonjs
