### ISSUE TITLE
Provide gesture to cause the host to rollforward to preview versions of the runtime

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3227]
In the CLI, we have many tests that target a particular (released) runtime, like project.json migration tests and because the host does not roll forward from a released version to a pre-release version, we end up having to put hacks in places to make these tests pass.

Could we consider adding a "gesture" that would allow the host to rollforward?

**Comment by livarcocc** [comment]
Yes, we could specify a version if there is some global mechanism to do that.

cc @nguerrera

**Comment by nguerrera** [comment]
While it would work, I think we'd lose some test coverage.

Let's take an example. Suppose the 2.0 branch is moving from 2.0.5 to 2.0.6-servicing-1234 on the way to 2.0.6. If we test the middle version using a gesture that says "just use 2.0.6-servicing-1234" instead of "allow roll-forward to pre-release", then we're not simulating what would happen when 2.0.6 is ingested. And that simulation is the point of ingesting an unstable patch release.

**Comment by steveharter** [comment]
Closing and tracking with https://github.com/dotnet/core-setup/issues/3469
