### ISSUE TITLE
Detecting if .Net Core Runtime is installed, reliably

### ISSUE THREAD

**Issue by angelsix** [dotnet/core-setup#3265]
I'm creating a Wix installer, and it appears nobody has any solid way to detect if the .Net Core runtime is installed on a machine...?

Now I don't want to package my application with publish -r and have the entire framework in the folder for every application, I would prefer to have the client install the .Net Core runtime (or do it for them).

1. Is that the correct approach/expected way to distribute .Net Core apps to the outside world? i.e. with dotnet publish (no -r) and have the runtime installed on the clients machine, like .Net Framework does.

2. If so, there appears no registry entry, no system flag, no hard-folder path for determining if .Net Core Runtime is installed. So how do we detect it for an installer prerequisite?

Some people look at hard-coded paths like C:\Program Files\dotnet\shared\Microsoft.NETCore.App however that can change and is not localized either so won't work well.

I've spotted a few registry entries but nothing I feel confident in ascertaining the installed versions of .Net Core from without confirmation.

So can anyone shed some light on a solid future-proof way of detecting the presence of .Net Core runtimes on a machine?

**Comment by Petermarcu** [comment]
@rakeshsinghranchi , do you have any guidance for this? I don't see anything obvious in the installers that was added to make detection easier.

**Comment by rakeshsinghranchi** [comment]
Below key existence can be used for runtime detection : 
SOFTWARE\dotnet\Setup\InstalledVersions\**x64**\sharedfx\Microsoft.NETCore.App\**2.0.0**

https://github.com/rakeshsinghranchi/core-setup/blob/master/src/pkg/packaging/windows/sharedframework/registrykeys.wxs#L7

**Comment by Petermarcu** [comment]
How do people deal with patched SxS versions?

**Comment by jimmyca15** [comment]
There should be a registry hive that maps all incompatible .NET Core runtimes to their latest installed version.

I.e. something that looks like this:

1.0.* -> 1.0.7
1.1.* -> 1.1.4
2.0.* -> 2.0.0

This is the information that people who depend on .NET Core being on the machine depend on.

The reg key that you mentioned _SOFTWARE\dotnet\Setup\InstalledVersions*x64*\sharedfx\Microsoft.NETCore.App*2.0.0*_ doesn't help with this case.

Installer logic should be
1. I depend on .NET Core 1.0.3 or above
2. Get value of key: SOFTWARE\dotnet\Setup\InstalledVersions*x64*\sharedfx\Microsoft.NETCore.App\1.0.*
3. Is value >= 1.0.3

Trying to figure out if .NET Core 1.0.* is installed on a machine right now is bad. We need to make it better.

Let me know if this info is already available. I haven't been able to find it since .NET Core 1.0.0

**Comment by jimmyca15** [comment]
Please let me know if I should file a new issue, but i believe I have the same concern as the original topic and it has not been fully addressed.
