### ISSUE TITLE
CI failure for tizen to publish nupkg

### ISSUE THREAD

**Issue by ragmani** [dotnet/core-setup#3354]
@eerhardt Recently [ci](http://52.79.132.74:8080/job/release/job/core-setup_master_armel_Release/211/) failed to publish nuget packages of core-setup for tizen.
So compared to [core-setup prtest ci](https://ci.dot.net/job/dotnet_core-setup/job/master/job/release_tizen_armel_prtest/1065/) in ci.dot.net, which is still a success, we saw that the build scripts are different and that the build script has changed recently by #3266.
- The CI for publishing
build.sh -ConfigurationGroup=Release -TargetArchitecture=armel
**-DistroRid=tizen.4.0.0-armel** 
-SkipTests=true -DisableCrossgen=true -PortableBuild=false -CrossBuild=true 
-OfficialBuildId=20171025-07
-- /p:OverridePackageSource=https:%2F%2Ftizen.myget.org/F/dotnet-core/api/v3/index.json **/p:Authors=Tizen**
- The CI for prtest in ci.dot.net
./build.sh -ConfigurationGroup=Release -TargetArchitecture=armel
**-strip-symbols**
-SkipTests=true -DisableCrossgen=true -PortableBuild=false -CrossBuild=true
-- /p:OverridePackageSource=https:%2F%2Ftizen.myget.org/F/dotnet-core/api/v3/index.json **/p:OutputRid=tizen.4.0.0-armel**

We have two questions about it.
1. What is the '-strip-symbols' option?
2. Is the 'DistroRid' option changed to 'OutputRid'?

cc @hqueue @hseok-oh @chunseoklee

**Comment by eerhardt** [comment]
> What is the '-strip-symbols' option?

This option removes the symbols from the native binaries during the build.  See
https://github.com/dotnet/core-setup/blob/b5dd381dd3a586640e4bfe4804d6563861eaab20/src/settings.cmake#L73

This is the same as the `stripSymbols` build option in `dotnet/coreclr` and `dotnet/corefx`.

> Is the 'DistroRid' option changed to 'OutputRid'?

Yes.  `DistroRid` was a bad name for this property, since it is ambiguous between "the distro we are building on" vs. "the distro we are building for".  `OutputRid` is pretty obvious that this is the Rid we are building for.

**Comment by hqueue** [comment]
@eerhardt Thanks for the explanation!

@ragmani I think we can just use `OutputRid` instead `DistroRid` and let's discuss about using `-strip-symbols` after comparing size of binaries.

**Comment by ragmani** [comment]
@eerhardt Thanks for your reply.
@hqueue Okay, I see.
