### ISSUE TITLE
Detecting if .Net Core Runtime is installed

### ISSUE THREAD

**Issue by jimmyca15** [dotnet/core-setup#3381]
This issue is a follow up to the comments I made on #3265.

### Scenario 
A developer creates an application that depends on .NET Core 1.0.* being installed on the machine.

### What Installers Should Do
Check the registry to confirm that .NET Core 1.0.* is present, then install the application.

### Explanation of Problem
What would be expected here is a registry key which maps to the latest installed version of .NET Core 1.0.*.

Right now registry keys are dumped at _HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App_ in the following manner

Microsoft.NETCore.App
  |
  | -  1.0.0-rc2
  | -  1.0.3
  | -  1.0.4
  | -  1.1.0
  | -  1.1.1

The problem with this method is that currently the latest 1.0.* version is 1.0.7. So if installers want to detect if 1.0.* is installed they need to check if 1.0.0 is installed or 1.0.1 is installed or 1.0.2 is installed or 1.0.3 is installed or 1.0.4 is installed or 1.0.5 is installed or 1.0.6 is installed or 1.0.7 is installed. Thats not all, because they need to plan for the release of 1.0.8 so they need to see if 1.0.8 is installed and there may be a 1.0.9 so they need to see if 1.0.9 is installed and there is no stopping point.

There is one way to solve this problem.

### Solution
A registry key who's name maps to a minor version of the .NET Core runtime.

Example:

_HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App\\_
__1.0.*__ -> 1.0.7

**Comment by steveharter** [comment]
@rakeshsinghranchi, any further suggestions or comments on making it easier to detect the version installed?

**Comment by Petermarcu** [comment]
The challenge here is that each runtime is installed side by side and we go to a lot of effort to have shared state in any place outside the host. We could try to have the global installers run a command in them that queries the host for the latest active version on any version train and write that somewhere that installers could detect. This would make the shared state not part of the installer technology (MSI) itself and just a follow up step in the installer.

**Comment by jimmyca15** [comment]
If the follow up step places it for each compatible version, 1.0.*, 1.1.*, and 2.0.* then that sounds like the solution to me. Then we can stop hard-coding our installers to check for the existence of the reg keys 1.0.0 - 1.0.99 since we depend on .NET Core 1.0.*

**Comment by tristanbarcelon** [comment]
@Petermarcu I too have this need to detect for presence of .Net core runtime and Windows Server Hosting packages, so I devised a detection logic in Powershell utilizing Ed Wilson's powershell function for enumerating properties and values of a registry key/subkey from [here](https://blogs.technet.microsoft.com/heyscriptingguy/2012/05/11/use-powershell-to-enumerate-registry-property-values/).

Assuming  my desired Major.Minor version string is '1.0.\*', the dotnetcore runtime detection script is as follows:
`

[string] $DesiredVersion = '1.0.\*'

if (Test-Path -Path 'HKLM:\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App' -PathType Container)
{
        [string] $DetectedVersion = Get-RegistryKeyPropertiesAndValues -path 'HKLM:\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App' | Where-Object { $_.Value -eq 1 -and $_.Property -Like $DesiredVersion } | Sort-Object -Property $_.Property -Descending | Select-Object -ExpandProperty Property -Last 1
}

if ([string]::IsNullOrEmpty($DesiredVersion))
{
    Write-Host "A compatible dotnetcore runtime $DesiredVersion could not be found in your system"
}

`

Some observations/questions with this logic:

1). I installed the following x64 builds of runtime versions 1.0.1, 1.0.0-rc2, 1.0.3, 1.0.8, 1.1.5, 2.0.0, 2.0.3 the on a 64bit system. All the registry entries are being stored in the 32bit section of the SOFTWARE hive 'HKLM:\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App' instead of the 64bit section. Is this always going to be the case?

2). Is it necessary for me to filter by a property value of 1? What would happen if I uninstall 1.0.1? Would it leave the registry value for 1.0.1 behind but with a value of 0?

3). The application metadata displayed by Add/Remove Programs is also stored in the 32bit section of the SOFTWARE hive. I'm checking for them in 'HKLM:SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall'. Furthermore, the DisplayVersion property somewhat changed in .dotnetcore 2.x. Prior to 2.x, the DisplayVersion string consistently displayed the semantic version before Runtime.

![image](https://user-images.githubusercontent.com/5810165/33899164-a86e0830-df38-11e7-9e84-20333b7317b8.png)

Detection script I used
`

$registrypath = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
        $registry32 = [microsoft.win32.registrykey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry32)
        $key = $registry32.OpenSubKey($registrypath) 
        $subKeys = $key.GetSubKeyNames() | ForEach-Object {
                $subKeyPath = $registrypath + "\\" + $_
                $packageKey = $registry32.OpenSubKey($subKeyPath) 
                $package = New-Object PSObject
                $package | Add-Member -MemberType NoteProperty -Name "DisplayName" -Value $($packageKey.GetValue("DisplayName"))
                $package | Add-Member -MemberType NoteProperty -Name "DisplayVersion" -Value $($packageKey.GetValue("DisplayVersion"))
                $package | Add-Member -MemberType NoteProperty -Name "InstallDate" -Value $($packageKey.GetValue("InstallDate"))
				$x86programs += $package    
        }

        if ($registry32 -ne $null) { $registry32.close() }
        if ($key -ne $null) { $key.close() }
        if ($packagekey -ne $null) { $packagekey.close() }

        $matches = $x86programs.Where({$_.DisplayName -Like "Microsoft .NET Core*Runtime*" })

        if ($matches.count -gt 0)
        {
            Write-Verbose "Following .NetCore runtime versions are already installed. Skipping installation"
			$matches | Format-Table
            return $true
        }

`

4). When detecting installed Windows Server Hosting versions that are installed, I'm finding that the installers are correctly installing to the right section of the registry hive.
64 and 32bit builds of the same package store their version information in
'HKLM:\SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedhost' and 'HKLM:\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedhost' respectively. Furthermore, when I install a newer version of the package, it supercedes the older version. The reverse is not true and the installer will not proceed. Can I count on this behavior to be consistent?

5). I haven't yet tried a separate install of ANCM and I do not know which registry key to use to detect the version. Would you be able to share that?

6). As a follow up to question 4, what displayname string can I use to detect installations of Windows  Windows Server Hosting packages in the registry?

Thanks in advance.

**Comment by Petermarcu** [comment]
@rakeshsinghranchi to get some of these answered. I believe the installer is 32bit which means it writes to the 32bit hive. @rakeshsinghranchi can confirm if that will always be the case. If there is ever a system that doesn't support a 32bit hive, it obviously would have to change.

@joeloff to answer questions about ANCM installer.

**Comment by tristanbarcelon** [comment]
Thanks @Petermarcu 

What would be a proper way to detect dependencies during deployment of .net core/asp.net core apps? We would like to keep developer machines in sync with deployment targets and one way I thought of achieving that is by pinning the versions of SDK and Server Hosting bundles installed on both dev machines and deployment targets. Given that the SDK and Server Hosting bundle both install the runtime(s) and asp.net package store(s), what differentiates the two bundles in terms of the things they install other than ANCM?  I think Visual Studio 2017 installs a different ANCM which works with IIS express. As far as I can tell, dotnet.exe is also installed by Server Hosting bundle and the runtime (please correct me here if I'm wrong). For framework dependent deployments, we need the dotnet.exe and ANCM.

Here's what I've also been able to find out in the meantime regarding Windows Server Hosting Package exe-based installers after some digging into github. I wanted to know if these are always the case so I can firm up the detection logic we are using.

1). The 2.0* versions does not respect the OPT_INSTALL_LTS_REDIST and OPT_INSTALL_FTS_REDIST flags anymore as referenced in [issue 848](https://github.com/dotnet/core/issues/848). This means that our deployment-time .NetCore version requirement check will have to be satisfied by checking specific Program Files\dotnet folders. Is this another way of checking for installed semantec versions of .net core runtime? How can I detect versions of of asp.net core runtime package store (RPS)? From what I can tell, version 2.0.3 of RPS installs nuget packages of various versions in dotnet\store\x64\netcoreapp2.0 though in reality, a developer could have referenced an assembly from version 2.0.0 and I won't be able to detect this until deployment time when something fails.

2). Detecting the version of Windows Server Hosting bundle is possible using [method](https://gallery.technet.microsoft.com/How-to-determine-ASPNET-512379b5) provided by onescript team, but the exact semantic version is not easily obtained. As you will see in this image, I installed 2.0.3 but the only place where 2.0.3 could be found is in the registry subkey **HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Updates\.NET Core\Microsoft .NET Core 2.0.3 - Windows Server Hosting**. I think this key might have also been installed **HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Updates\.NET Core\Microsoft ASP.NET Core 2.0.3 - Runtime Package Store (x64)**. Packageversion is close but any logic which parses that might break. I'm not that great with regex extraction, so between the two it would be easier for me to take the value of PackageVersion, split the values by dot, take the first 3 digits and finally just a substring of the 3rd digit. However, if the patch number of Windows Server Hosting does go past 9, this logic won't work anymore. Is regex extraction the only way of getting the semantic version of installed Windows Server Hosting bundles on the machine?

![image](https://user-images.githubusercontent.com/5810165/33993347-1955878c-e0a4-11e7-83f5-f17a19497c79.png)

3). ANCM doesn't have a separate installer published for any of the RTM/RTW versions so we have to peg it on the version of Windows Server Hosting bundle being installed. This means we have to manage the version of this bundle on dev machines too, though we might be in trouble in case there are mutiple versions of hosting bundle and RPS installed and the apps reference a different package from the store.

4). ASP.Net Runtime Package Store has separate installers, but its semantic version are not reflected in the version of Windows Server Hosting bundle. The bundle appears to encode the versions of .Net framework runtime it is installing. For example, installing DotNetCore.1.0.8_1.1.5-WindowsHosting.exe will install both the 1.0.8 and 1.1.5 runtimes. Based on the Server Hosting bundle detection logic from OneScript team, we get a new key in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Updates\.NET Core\Microsoft .NET Core 1.1.5 - Windows Server Hosting.

5). Based on this [link](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#install-the-net-core-windows-server-hosting-bundle), Windows Server Hosting bundle installs .net core runtime, .net core library, and ANCM. I'm clear on the runtime and ANCM, but what is the .Net core library it installs? Is that the Runtime Package Store? As far as I can tell on this [2.0.4 link](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.4-download.md) , it does install Runtime Package Store. The RPS bundling appears to have only started with 2.* versions of Windows Server Hosting bundle and the version of RPS could be different from Windows Server Hosting bundle. In the case of Hosting bundle 2.0.4, it is installing RPS 2.0.3.

Here's a function I wrote in Powershell utilizing some techniques I've found on the web. I still need to add ways for detecting RPS and ServerHosting bundle semantic versions based on  your feedback.

`Function Get-InstalledDotnetCoreVersion
{
    [CmdletBinding()]
    [OutputType([PSObject])]
    param()

    [Hashtable] $SDKVersions = [ordered] @{}
    [Hashtable] $RuntimeVersions = [ordered] @{}
    [Hashtable] $SFHVersions = [ordered] @{}

    try
    {
        # Got the ideas from here, but not using dotnet.exe --info or dotnet.exe --version and parsing its output
        # http://irisclasson.com/2017/06/27/net-core-finding-out-sdk-installed-runtime-and-framework-host-versions/
        # We're only dealing with Windows platform here and not linux and only packages using the installer method
        # will be detected. Zip packages will not be handled

        [string] $RootDotnetPath = Join-Path -Path $env:programfiles -ChildPath 'dotnet'
        [string] $SdkPath = Join-Path -Path $RootDotnetPath -ChildPath 'sdk'
        [string] $RuntimePath = Join-Path -Path $RootDotnetPath -ChildPath 'shared\Microsoft.NETCore.App'
        [string] $SFHPath = Join-Path -Path $RootDotnetPath -ChildPath 'host\fxr'

        if (Test-Path -Path $RootDotnetPath -PathType Container)
        {
            if (Test-Path -Path $SdkPath -PathType Container)
            {
                Write-Verbose "$($SdkPath) was found. Enumerating versions now."

                Get-ChildItem -Path $SdkPath -Directory | Where-Object { $_.Name -match '^\d{1}.\d{1}.\d{1}' }  | Sort-Object -Property Name | Foreach-Object { $SDKVersions.Add( $_.Name, $_.FullName ) }
            }

            if (Test-Path -Path $RuntimePath -PathType Container)
            {
                Write-Verbose "$($RuntimePath) was found. Enumerating versions now."

                Get-ChildItem -Path $RuntimePath -Directory | Where-Object { $_.Name -match '^\d{1}.\d{1}.\d{1}' } | Sort-Object -Property Name | Foreach-Object { $RuntimeVersions.Add( $_.Name, $_.FullName ) }
            }

            if (Test-Path -Path $SFHPath -PathType Container)
            {
                Write-Verbose "$($SFHPath) was found. Enumerating versions now."

                Get-ChildItem -Path $SFHPath -Directory | Where-Object { $_ -match '^\d{1}.\d{1}.\d{1}' } | Sort-Object -Property Name | Foreach-Object { $SFHVersions.Add( $_.Name, $_.FullName ) }
            }
        }
        
        [Hashtable] $Properties = @{ 'SDKVersions' = $SDKVersions;
            'RuntimeVersions' = $RuntimeVersions;
            'SharedFrameworkHostVersions' = $SFHVersions
        }

        $Result = New-Object -TypeName PSObject -Prop $Properties

        return $Result
    }
    catch
    {
        throw $_
    }
}`

Thanks in advance!

**Comment by joeloff** [comment]
@tristanbarcelon for ANCM, it will write a couple of registry key, but you can probably look at SOFTWARE\Microsoft\IIS Extensions\IIS AspNetCore Module. There should be an Install value set to 1, but there are also entries for the version present.

For RPS, we also write a key, mainly to record the version: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET Core\Runtime Package Store\v2.0. The RPS releases in 2.0 do support SxS installs, for example you can have both 2.0.0-preview1 and 2.0.0-RTM installed

You are correct that the LTS/FTS options aren't being honored in 2.x. This is mainly due to the fact that we don't currently have an officially declared LTS/FTS version like we do with the 1.x hosting bundle that shops both 1.0 and 1.1 runtimes. 

The keys for the hosting bundle itself only indicates that the bundle installer was run. Bundles are a bit strange in that regard. For example, if you install a bundle, but non of the individual MSIs it carries was found to be applicable, the bundle, albeit empty, would still be installed.

**Comment by tristanbarcelon** [comment]
Thanks @joeloff for the clarification.

I will be going over our IIS servers to test my updated detection logic.

In the meantime, I have refined our detection logic to essentially check the file system for runtime, fxr (i think this is shared framework host), sdk, and the registry for RPS and Windows Server Host.

1). Runtime versions
check Program Files\dotnet\shared\Microsoft.NETCore.App and enumerate all child folders that meet regex pattern ^\d.\d.\d

2). SDK versions
check Program Files\dotnet\sdk and enumerate all child folders that meet regex pattern ^\d.\d.\d

3). shared framework host
check Program Files\dotnet\host\fxr and enumerate all child folders that meet regex pattern ^\d.\d.\d

For RPS and Windows Server Hosting bundles, I interrogate this registry key as follows if it exists:

HKLM:\SOFTWARE\Wow6432Node\Microsoft\Updates\.NET Core'

when checking for RPS, I get all the subkeys from above that match this pattern: 'Microsoft ASP.NET Core*Runtime Package Store*'

when checking for Windows Server Hosting, the pattern is 'Microsoft .Net Core*Windows Server Hosting'

I get results like **Microsoft .NET Core 1.1.5 - Windows Server Hosting**, **Microsoft .NET Core 2.0.3 - Windows Server Hosting** or **Microsoft ASP.NET Core 2.0.3 - Runtime Package Store (x64)** so I use regex matching to extract the 3 digit numeric version from the string. I've attached the powershell script I now have for detecting installed versions of dotnetcore packages.

[DotnetCoreUtils.txt](https://github.com/dotnet/core-setup/files/1560592/DotnetCoreUtils.txt)

After I execute it, I have the following result.

![image](https://user-images.githubusercontent.com/5810165/34012593-6392e306-e0e2-11e7-9249-d403276ef512.png)

It's returning an object with 5 hashtable properties: one for Runtime, WindowsServerHosting, RPS, SharedFrameworkHosting, SDK.

I'm thinking that this result (when processed correctly) would serve me two purposes:

1). When aiming for equality amongst dev machines, build servers, and deployment targets we would look for exact matches of specific versions of runtime or server hosting.

2). When aiming for compatibility i would have to just compare a little differently ensuring that the deployment target has the same major.minor as expected but the patch number must be equal to or higher.

I'm not sure how to ensure how to prevent breakage at deployment or runtime because the apps themselves would reference specific versions of nuget packages in the RPS while RPS is versioned at the collective level. Is there some way to ensure that the devs only reference packages at the RPS level?

Tristan

**Comment by Wael72Daoud** [comment]
Hello all,
My question might not be a good fitting for this thread please feel free to direct me otherwise.
I would like to know the best way to deploy dotnet core patches/upgrade packages. It seems they don't respect upgrade intitled by the Windows Installer best practices. Basically, the newer version doesn't remove the older version of the machine, the user will end up having two installers on the machine, for my example:
 I was upgrading 2.1.6 run time --> 2.1.11 run time using the Windows Installer packages (my expectations were 2.1.6 will be removed off the machine after installing 2.1.11. but that never happened; Are you really trying to make me remove 2.1.6 before 2.1.11? if not what was the wisdom having all of these packages kept back my machine?

**Comment by joeloff** [comment]
@Wael72Daoud 1.x and 2.x was always intended to be side-by-side which is why it won't remove 2.1.6 when you install 2.1.11. In 3.0, starting with Preview 4 we support upgrades within a specific release band. For example, SDKs in the 3.0.0 range would upgrade, similarly for 3.0.100, etc. However something like 3.0.100 and 3.0.200 would be SxS

**Comment by dagood** [comment]
Closing, this seems like a stale discussion.
