### ISSUE TITLE
Unable to 'dotnet run' 2.0.0 app on 2.1 preview runtime

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3462]
_From @piers7 on November 28, 2017 13:46_

## Steps to reproduce
- pull [dotnet Alpine images](https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-prod-alpine-preview), containing 2.1 preview SDK/runtime
- use SDK container from above to build and publish console app targeting 'netcoreapp2.0' into runtime container
- start container containing published app (ie dotnet run 2.0 app on 2.1 preview runtime)

Trivial repro repo here: https://github.com/piers7/FSharpDotNetCore

## Expected behaviour
- Since target framework (2.0.0) not present, 'minor version roll forward' behaviour kicks in and uses the 2.1 preview runtime (as per [.net Core 2 Version Binding design doc](https://github.com/dotnet/designs/issues/3)).
- App runs, says Hello World etc...

## Actual behavior
App fails to run, with following error.
```
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - The .NET framework can be installed from:
      https://aka.ms/dotnet-download-runtime
  - The .NET framework and SDK can be installed from:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The following versions are installed:
      2.1.0-preview1-25919-02 at [/usr/share/dotnet/shared]
```

**Has this part of the versioning design just not been implemented yet? I'm finding it very hard to find any definitive doco on this.**

Full build log here: https://travis-ci.org/piers7/FSharpDotNetCore/builds/307411662

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.2.0-preview1-007582)

Product Information:
 Version:            2.2.0-preview1-007582
 Commit SHA-1 hash:  4845efe2ea

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.0-preview1-007582/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25919-02
  Build    : 96a1025de48784825ac61e45ece24a4343e0bf01
```

_Copied from original issue: dotnet/cli#8116_

**Comment by livarcocc** [comment]
This is not currently support. The runtime team is considering adding support for this in 2.1.0.

I will move this issue to core-setup.

cc @Petermarcu @steveharter

**Comment by Petermarcu** [comment]
We're likely going to need to apply the same principle across the release -> pre-release boundary where a higher minor of a pre-release could satisfy the request for a runtime if the one thats asked for isn't present.

**Comment by steveharter** [comment]
I think there is some risk to go from release to pre-release on minor in production scenarios unless explicit somehow. However, I understand this is useful for development scenario because tools etc aren't always up-to-date and don't generate the correct version numbers.

But we don't really know what the intent is -- do they just want one app to roll-forward, or all apps on the machine?

Thus another option like --roll-forward-on-no-candidate-fx may be appropriate, or add another value to that setting ('2') to denote release\pre-release mixing. That feature has command line, runtimeconfig.json and environment variable support already.

**Comment by Petermarcu** [comment]
I think we have to tell people in production to make sure they have a production runtime installed. If a production runtime is installed that supports their app, we should use that one. If not, running on pre-release should be ok.

**Comment by piers7** [comment]
@steveharter The 'Roll Forward On No Candidate Fx' design doc (March) seems to be at odds here with the 'Run a published application with the required runtime missing' section of (May) '[.NET Core 2+ Version Binding](https://github.com/dotnet/designs/issues/3)', which was the only document I originally found:

> You may run an application on a machine that is missing the runtime required by the application. If the required runtime is missing and a higher minor version is installed, the minor version should be used instead of failing to load the application. Higher major versions will not be used to load applications. This behavior shall be called "minor version roll-forward.

...though I appreciate this doesn't explicitly talk about pre-release scenarios. So at least someone needs to point one of those design docs at another, otherwise you'll presumably get a load of confused people like myself burning your time on github issues :-)

In terms of intent: as a user, I'd have no problems whatsoever with needing to 'force' the roll forward in preview scenarios (ie a cmd line flag), I just need a simple way to test against uplevel versions of the runtime without (ideally) having to hack the .*proj file to do so (or indeed without rebuilding at all).

As an aside, doesn't [this bit](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md#multilevel-sharedfx-lookup) (bottom of 'roll forward on no candidate fx' doc) suggest _major_ version roll forward? Or is this a typo:
```
Roll Forward On No Candidate Fx: enabled
Desired version: 1.0.1
Available versions in the current working dir: 1.0.0
Available versions in the user .NET location: 2.0.0
Available versions in the exe dir: 1.0.1
Chosen version: 2.0.0
```

**Comment by steveharter** [comment]
@piers7 there is a plan on support roll-forward of minor releases in the 2.1 timeline (so 2.0 will use 2.1 if 2.0 is not installed), but that is not the current behavior yet. The 'Roll Forward On No Candidate Fx' only talks about current behavior, unless specifically noted.

>I'd have no problems whatsoever with needing to 'force' the roll forward in preview scenarios (ie a cmd line flag)

Yes we need to work this out:
1) Is the roll-forward from preview to production on by default? (assuming yes)
2) Is it global across the machine? (assuming yes)
3) Does it have a mechanism to turn it off globally, and enable it via command-line or config for certain scenarios?
4) Is it odd to have both preview and production scenarios on the same machine?

> suggest major version roll forward?
Yes that feature will roll forward to the least version considering both major:minor, and then roll forward on patches if that is enabled.

**Comment by steveharter** [comment]
Closing this issue as it is covered by new issue https://github.com/dotnet/core-setup/issues/3469
