### ISSUE TITLE
Dotnet 'myApp.dll' hang running on arm32

### ISSUE THREAD

**Issue by jkotas** [dotnet/core-setup#3561]
_From @stevehayles on January 3, 2018 3:14_

Running a very framework dependent console application with the command 'dotnet myapp.dll' causes a hang running on a simple yocto image on an Rpi3 (arm32)

Running dotnet --info produces the expected output of 

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

but running any application including a very basic app that simply writes to the console completely hangs with zero output to the terminal.

Running with COREHOST_TRACE=1 produces similar output to what is seen running the app on another Linux machine but it hangs before the expected line "Property TRUSTED_PLATFORM_ASSEMBLIES = ...."

The 'installation' has been from the binary release at [https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-runtime-2.0.0-linux-arm.tar.gz](url)

The final few lines of output before hanging are

`Considering entry [runtime.linux-arm.Microsoft.NETCore.DotNetHostPolicy/2.0.0/runtimes/linux-arm/native/libhostpolicy.so] and probe dir [/opt/dotnet/shared/Microsoft.NETCore.App/2.0.0]
    Local path query exists /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0/libhostpolicy.so
    Probed deps json and matched '/opt/dotnet/shared/Microsoft.NETCore.App/2.0.0/libhostpolicy.so'
The resolved JIT path is '/opt/dotnet/shared/Microsoft.NETCore.App/2.0.0/libclrjit.so'
CoreCLR path = '/opt/dotnet/shared/Microsoft.NETCore.App/2.0.0/libcoreclr.so', CoreCLR dir = '/opt/dotnet/shared/Microsoft.NETCore.App/2.0.0/'`

At this stage ctrl+c has no effect and the process needs to be killed to recover the terminal

The full output is attached along with the application

[output.txt](https://github.com/dotnet/coreclr/files/1599325/output.txt)
[testApp.zip](https://github.com/dotnet/coreclr/files/1599326/testApp.zip)

_Copied from original issue: dotnet/coreclr#15693_

**Comment by jkotas** [comment]
> it hangs before the expected line "Property TRUSTED_PLATFORM_ASSEMBLIES = ...."

This seems to hang in the `dotnet` host before the control reaches CoreCLR.

@stevehayles Here are a few things that would help us to diagnose this further:
- Would it be possible to attach native debugger to the hung process (gdb or lldb) and see where it is stuck? 
- Does it hang for standalone apps as well on your system (https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md)?

@Petermarcu Have you seen a hang like this on Rpi?

**Comment by Petermarcu** [comment]
I haven't. @stevehayles, can you share the output of `lscpu`?

**Comment by stevehayles** [comment]
Shortly after my original post I managed to attach a debugger it showed the main dotnet thread and 2 threads that were calling into lttng-ust.  I am no expert in native debugging but the lttng-ust references seemed like a good starting point.

I have compiled coreclr, corefx and corehost for the Rpi in a Yocto image and I'm currently trying to build Coreclr now with the -DFEATURE_EVENT_TRACE=0 but it's very slow and won't be ready for some hours.

The good news is that simply removing the lttng-ust library from the OS allows the applications to start and run normally (including a much more complex MVC example).

Not great fault-finding but I am happy to do more and will post the results of the build with event tracing disabled

In answer to your specific questions @jkotas the 'hang' was identical in behaviour for any self-contained or framework-dependent app that I tried.  

C# on Arm architecture is am amazing development so I thank you for all your good work

**Comment by Petermarcu** [comment]
In case you didn't see it. There are instructions for how to use the pre-built binaries on Yocto. https://github.com/dotnet/core/blob/master/samples/YoctoInstructions.md

**Comment by jkotas** [comment]
> I managed to attach a debugger it showed the main dotnet thread and 2 threads that were calling into lttng-ust.

Thanks. This is a problem in CoreCLR after all. I am going to close the issue here, and reactivate the one in CoreCLR.

**Comment by stevehayles** [comment]
@Petermarcu Thanks for the information, I am achieving a similar result using RDEPENDS within a custom Yocto layer rather than using CORE_IMAGE_EXTRA_INSTALL.

You have raised what I think is a very relevant point here in that the dependencies within those instructions do not include lttng-ust.  I would not have seen this issue had I used those instructions explicitly but it does still point towards event tracing causing issues on Arm architecture.

This topic is closed now but in answer to your previous question, I don't have lscpu but the following is from /proc/cpuinfo

processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial		: 0000000085d24077

**Comment by Petermarcu** [comment]
@wfurt as FYI - @wfurt has done work on Yocto. Also @brianrob who is an expert on tracing.

**Comment by pauldotknopf** [comment]
Am I experiencing this same issue with #4484?

@stevehayles, did ```-DFEATURE_EVENT_TRACE=0``` work for you?

**Comment by stevehayles** [comment]
@pauldotknopf, I moved to the binary releases for my build but yes using -DFEATURE_EVENT_TRACE=0 worked fine. 

Within my Yocto built arm32 system (on Rpi3) if I remove all traces of lttng from the image the current binary releases work fine but something is broken around lttng and if it's included in the image then the same 'bug' is still present.
