### ISSUE TITLE
Microsoft.Extensions.DependencyModel: Newtonsoft.Json version conflict between 9.0.x and 10.0.x

### ISSUE THREAD

**Issue by Schaeri** [dotnet/core-setup#3597]
The Microsoft.Extensions.DependencyModel (2.0.4) depends on the Newtonsoft.Json version 9.0.x. The problem is that other packages used for an ASP.Net Core application use the newer 10.0.x version. For example Microsoft.AspNetCore.JsonPatch and Microsoft.AspNetCore.Mvc.Formatters.Json. Now we have to do assembly redirects which solves the build warnings but could lead to runtime problems. Is it not possible to upgrade this packages with the new version and align all the packages to use the same Newtonsoft.Json version?

Thanks for the support

**Comment by steveharter** [comment]
FYI @eerhardt

**Comment by eerhardt** [comment]
@Schaeri - I assume you are talking about the full .NET Desktop framework when you mention assembly redirects.  Correct?

In general, we are referencing the lowest possible version of dependencies that will work.  DependencyModel doesn't require using a newer Newtonsoft.Json.  So if DependencyModel upgraded its version of Newtonsoft.Json, just because there is a new version, it would mean all consumers of DependencyModel need to use the new version as well.

Another note is that there are more consumers of DependencyModel than just ASP.NET Core assemblies.  So upgrading these references affect more than just ASP.NET apps.

Is there something concretely broken with DependencyModel depending on Newtonsoft.Json `9.x`?  Or is your concern just that an app needs to use binding redirects, which may cause problems in the future?

**Comment by Schaeri** [comment]
Thanks for your answer. Yes we are using the Full .Net Desktop framework with the old project format. We are using Asp.Net Core MVC in our project. Currently there is nothing broken and everything seems to work. I understand your point that the DependencyModel is used by many other projects and you try to use the lowest version possible. But on the other hand the only package we install via NuGet is the Asp.Net Core MVC and then we have to add some assembly redirects to remove all our warnings and runtime issues. This is somehow annoying and take a lot of time in a very big project using a lot of nuget package. Our application configuration files contain a lot of redirects and the package update process is very time consuming. But it is like it is.
