### ISSUE TITLE
Core-Setup-Linux-BT build leg went from 28 min to 90 min

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3693]
In Build 20180209-04, the Linux-BT build leg took 28 min
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1370284

The next build 20180210-01, the same leg took 91 min
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1372444

And has been taking that long since.

Looking at the change list between these two builds

https://github.com/dotnet/core-setup/compare/5df6e9b7ab674a461b2a7f01ac87fb6e0ca06666...26f3b04c9af628920f7740413083d9318197f386

There was only 1 change - to update corefx, buildtools and WCF.

My guess is the buildtools between versions

-2.1.0-preview2-02507-02
+2.1.0-preview2-02509-01

caused this. Specifically https://github.com/dotnet/buildtools/pull/1904

If it is, we should implement my suggestion in https://github.com/dotnet/buildtools/issues/1788 - 

> Lucky for us, Azure Storage already has this functionality built in, we don't need to do it ourselves.  Instead we should be using [`AccessCondition.GenerateIfNotExistsCondition()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.accesscondition.generateifnotexistscondition?view=azure-dotnet#Microsoft_WindowsAzure_Storage_AccessCondition_GenerateIfNotExistsCondition) and let Azure do the check for us.

/cc @rakeshsinghranchi @MattGal @weshaggard

**Comment by MattGal** [comment]
How many blobs are in the container you’re using?  Even with tens of thousands of blobs, enumerating them all takes seconds.

**Comment by MattGal** [comment]
Probably accurate.  The dotnetcli/dotnet container does contain 495719 blobs;  previously before I fixed the bug it would be fetching ~5000 of these tops.

On wifi, during STRIKE training, enumerating all those blobs using the build task took 150s (2:30)

It would be very easy to change this task to use the SDK client libraries, but I think folks want to do other changes to separate out the tasks first (would be super easy to put a more efficient implementation only into the CloudTestTasks package, though)

**Comment by weshaggard** [comment]
@MattGal Can you help me understand why we need to download all blobs, as opposed to a filtered view of them?

**Comment by MattGal** [comment]
Note it's just getting the list of the blobs, but we definitely don't need to download them all, I was simply fixing a bug in the original (lazyish) implementation which is now restored.  It will now, if the blob it's asked to upload is not in the first 4-5000 blobs, overwrite the blobs regardless of the setting of the "overwrite" or idempotency flags.  

The implementation depended on this approach because it was implemented with containers that had < 2000 blobs, so performance was never an issue (fetching metadata on 450K is a lot), and it intended to know in advance 1) if it was being asked to overwrite a blob, so it could error if that happened unexpectedly and 2) to download blobs that might be identical (i.e. their relative path already existed) and not fail in this case.

**Comment by steveharter** [comment]
Should we target this to be fixed for 2.1?

**Comment by weshaggard** [comment]
This was fixed already.
