### ISSUE TITLE
Need to keep README up to date with servicing releases

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3822]
## Steps to reproduce
Go to https://github.com/dotnet/core-setup#daily-builds

Inspect and download the latest "Release/2.0.X" build/version.

## Expected  behavior
It should be the latest.

## Actual behavior
It is not the latest. Right now it says `2.0.4`, but `2.0.5` has been shipped for a few months.

/cc @weshaggard @leecow @wtgodbe

**Comment by eerhardt** [comment]
Even worse, the `dotnet-install` script doesn't seem to be kept up to date either:

```
> C:\Users\eerhardt\Downloads\dotnet-install.ps1 -DryRun -Channel release/2.0.0 -SharedRuntime
dotnet-install: Payload URLs:
dotnet-install: Primary - https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.4/dotnet-runtime-2.0.4-win-x64.zip
dotnet-install: Legacy - https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.4/dotnet-win-x64.2.0.4.zip
dotnet-install: Repeatable invocation: .\C:\Users\eerhardt\Downloads\dotnet-install.ps1 -DryRun -Channel release/2.0.0 -SharedRuntime
```

**Comment by nguerrera** [comment]
cc @johnbeisner, @livarcocc , @leecow on `dotnet-install`. IIRC there is that there is a step in the servicing release process for updating the channel.

**Comment by livarcocc** [comment]
1.1.8 release tag was created yesterday and @peterhuene sent you an email with a link to it.

I haven't had a chance to create the 2.1.101 tag yet, will do so tomorrow.

**Comment by leecow** [comment]
@livarcocc - the 2.1.101 tag was already created. https://github.com/dotnet/cli/commit/6c22303bf084f75dd7cd9dc744449054dddb8c8e 

I'm seeing that 'latest' dl links on core-setup are downloading the 2.1.0-preview, 2.0.7-servicing, 1.1.8-servicing and 1.0.11-servicing which is the expected behavior. 

The various latest.version files have all been updated so whatever they drive should now be correct.
