### ISSUE TITLE
2.1 runtime location: the required library libhostfxr.so could not be found

### ISSUE THREAD

**Issue by tmds** [dotnet/core-setup#4078]
Using daily dotnet build, and installing dotnet-watch rc tool from nuget feed I get this:
```
/tmp/tools$ which dotnet
~/dotnet-latest/dotnet

/tmp/tools$ dotnet --version
2.2.100-preview1-008633

/tmp/tools$ dotnet tool install --tool-path /tmp/tools --source-feed https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json --version 2.1-rc1-30677 dotnet-watch
Format version is missing. This tool may not be supported in this SDK version. Please contact the author of the tool.
You can invoke the tool using the following command: dotnet-watch
Tool 'dotnet-watch' (version '2.1.0-rc1-30677') was successfully installed.

/tmp/tools$ ./dotnet-watch 
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/tmp/tools/.store/dotnet-watch/2.1.0-rc1-30677/dotnet-watch/2.1.0-rc1-30677/tools/any/any/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```
My expectation is this app should pick up the dotnet root based on the `dotnet` executable which is on my PATH.

CC @steveharter @wli3 @eerhardt @omajid

**Comment by tmds** [comment]
The source-builds we are doing for RHEL, CentOS and Fedora don't have `dotnet` at `/usr/share/dotnet`.

**Comment by eerhardt** [comment]
> or use the DOTNET_ROOT environment variable to specify the runtime location.

That's the environment variable that can be used to set the path to the runtime location.  We don't probe the `$PATH` environment variable, since that is for finding executables.  In this scenario, you've already found the executable you want to run - `/tmp/tools$ ./dotnet-watch`, so the `$PATH` shouldn't come into play.

When we were designing the DOTNET_ROOT feature, we also had the idea to allow the `/usr/share/dotnet` path to be specified at build-time of `dotnet/core-setup`.  Meaning that RedHat (or any other distro) could provide their default installation path during source-build, and this would be the default location stamped into the apphost executable.  However, I believe that feature got cut.

**Comment by tmds** [comment]
> this would be the default location stamped into the apphost executable

Where does the `apphost` executable live in the SDK that is used for `dotnet tool install`? This `apphost` is different from the one used for `dotnet publish`ing self-contained? That one comes from nuget.org, right?

> I believe that feature got cut.

So what are our options to make this work for source-build .NET Core?

**Comment by natemcmaster** [comment]
FYI the same issue applies to Windows builds too. https://github.com/dotnet/cli/issues/9114

**Comment by tmds** [comment]
Closing as dup of https://github.com/dotnet/cli/issues/9114.
