### ISSUE TITLE
Filenames in dowload link to include version instead of latest

### ISSUE THREAD

**Issue by ghost** [dotnet/core-setup#4148]
In the README, there is:

|  |  |
|---| -----------|
| 1.0 | https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-win-x64.latest.zip |
| 1.1 | https://dotnetcli.blob.core.windows.net/dotnet/release/1.1.0/Binaries/Latest/dotnet-win-x64.latest.zip |
| 2.0 | https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.0.0/dotnet-runtime-latest-win-x64.zip |
| 2.1 | https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.1/dotnet-runtime-latest-win-x64.zip |
| master | https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.zip |

each file having the name `dotnet-runtime-latest-win-x64.zip`. Can we instead have `dotnet-runtime-<version>-win-x64.zip`? Where `<version>` is the actual latest version like 2.0.7 for 2.0 and in case of master, the short (7 digits) commit hash (`git rev-parse --short=7 HEAD`)?

**Comment by dagood** [comment]
We can't: including the version would require the readme.md content to change after every build, and since readme.md is checked into source control, this is undesirable. We actually take pains in publish infra to replace the version with `latest` so we can link them in the readme!

(1.0/1.1 were quirky for historical reasons, but now they're EOL.)
