### ISSUE TITLE
dotnet --info only finds same architecture, and lists entries twice when called with absolute path.

### ISSUE THREAD

**Issue by markusschaber** [dotnet/core-setup#4154]
## Steps to reproduce
call "dotnet --info" or "C:\Absolute\Path\to\dotnet.exe --info"

See https://gist.github.com/markusschaber/480879b83ec9a22077c6c31e3d7f8346 for full repro.

## Expected  behavior
All installed SDKs and runtimes are listed exactly once.

## Actual behavior
When calling without absolute path, only the SDKs and runtimes of the same architecture (e. G. x86 vs x64) are listed.

When calling with absolute path, it also only finds the SDKs and runtimes of the same architecture, but lists all of them twice.

## Environment data
Microsoft Windows [Version 6.1.7601], 64 bit (x64).

**Comment by markusschaber** [comment]
Remark: I filed this report as recommended on gitter (https://gitter.im/dotnet/coreclr) - I'll be on holiday for the next to weeks, with only limited ability to monitor this issue. Thanks for your patience.

**Comment by steveharter** [comment]
On`C:\Absolute\Path\to\dotnet.exe` showing duplicate entries: if the path exactly matches (casing included) a previous entry, then it is not shown. In the example `c:` was used for the path of `dotnet.exe` while the physical disk is `C:` causing two entries to be found. We can attempt to filter ignoring case on Windows, but on Unix we can't since the file system can be case-sensitive.

**Comment by markusschaber** [comment]
Maybe the pathes could be normalized, like the System.IO.Path.GetFullPath() method does on the classic .NET?

**Comment by leecow** [comment]
Issue moved to [dotnet/coreclr #18466](https://github.com/dotnet/coreclr/issues/18466) via [**ZenHub**](https://www.zenhub.com/)
