### ISSUE TITLE
dotnet --info only finds same architecture, and lists entries twice when called with absolute path.

### ISSUE THREAD

**Issue by jkotas** [dotnet/core-setup#4236]
_From @leecow on June 14, 2018 16:38_

@markusschaber commented on [Fri May 18 2018](https://github.com/dotnet/core-setup/issues/4154)

## Steps to reproduce
call "dotnet --info" or "C:\Absolute\Path\to\dotnet.exe --info"

See https://gist.github.com/markusschaber/480879b83ec9a22077c6c31e3d7f8346 for full repro.

## Expected  behavior
All installed SDKs and runtimes are listed exactly once.

## Actual behavior
When calling without absolute path, only the SDKs and runtimes of the same architecture (e. G. x86 vs x64) are listed.

When calling with absolute path, it also only finds the SDKs and runtimes of the same architecture, but lists all of them twice.

## Environment data
Microsoft Windows [Version 6.1.7601], 64 bit (x64).

---

@markusschaber commented on [Fri May 18 2018](https://github.com/dotnet/core-setup/issues/4154#issuecomment-390234367)

Remark: I filed this report as recommended on gitter (https://gitter.im/dotnet/coreclr) - I'll be on holiday for the next to weeks, with only limited ability to monitor this issue. Thanks for your patience.

---

@steveharter commented on [Mon May 21 2018](https://github.com/dotnet/core-setup/issues/4154#issuecomment-390657990)

On`C:\Absolute\Path\to\dotnet.exe` showing duplicate entries: if the path exactly matches (casing included) a previous entry, then it is not shown. In the example `c:` was used for the path of `dotnet.exe` while the physical disk is `C:` causing two entries to be found. We can attempt to filter ignoring case on Windows, but on Unix we can't since the file system can be case-sensitive.

---

@markusschaber commented on [Wed May 23 2018](https://github.com/dotnet/core-setup/issues/4154#issuecomment-391433151)

Maybe the pathes could be normalized, like the System.IO.Path.GetFullPath() method does on the classic .NET? This could also resolve symlinks etc...

_Copied from original issue: dotnet/coreclr#18466_

**Comment by steveharter** [comment]
@markusschaber my recommendation is to remove the duplicated entries as suggested with realpath.

However, I do not recommend showing both x64 and x86 frameworks in the same list, because the instance of dotnet.exe being used will only look in either the x64 or x86 folder for compatible frameworks, not both. 

I do understand that "accidently" running the x86 version instead of x64 is an issue, however. Some options to address this is to more clearly state that in `dotnet --info` in some manner, or perhaps have the installer ensure x64 is before x86 in %PATH%

@rakeshsinghranchi would it be possible to ensure x64 (`C:\Program Files\dotnet`) is before x86 (C:\Program Files (x86)\dotnet`) in %PATH% when both are installed? I believe this is becoming more common as because the ASP.NET hosting bundle are currently installing both.

**Comment by markusschaber** [comment]
@steveharter Actually, on our case, we have some 32 bit native libraries which are not ported to 64 bit yet. (It's already in progress, however).

So we very confused at the beginning that it worked on some machines, but not on others, despite the fact that we had set x86 architecture and everything in the project settings, VS target selection etc.

So part of the problem is that the toolchain (dotnet and VS) ignore the architecture setting even if both architectures are installed.

Of course, our workaround was to rearrange the PATH entries, at the cost of not being able to run other projects in 64 bit on those dev machines.

I think it should be possible for a dotnet to detect runtimes / SDKs for other installed architectures, and then just forward the call to them in case...

**Comment by steveharter** [comment]
>> Of course, our workaround was to rearrange the PATH entries, at the cost of not being able to run other projects in 64 bit on those dev machines.

So was it install order across the different machines that caused %PATH% to vary? Having a consistent order may be useful (e.g. 64-bit always first set by the installer).

>> I think it should be possible for a dotnet to detect runtimes / SDKs for other installed architectures, and then just forward the call to them in case...

I'm not sure how that would work, since we don't really know the intent (32- or 64-). And we can't really forward unless we launch a new process. It's part of the (common) pain of supporting both 32- and 64-bit.

@nguerrera do you have any feedback here? I know our internal tooling has issues with switching between 32- and 64-bit.

**Comment by steveharter** [comment]
Also I have a PR ready that fixes the casing issue. It turns out that we already do the equivalent of "realpath" but on Windows it doesn't normalize the casing to what is on the file system, so the PR just does a case-insensitive compare on Windows.

**Comment by nguerrera** [comment]
I've been wondering if this would help:

```
C:\Program Files\dotnet
    dotnet.exe
    dotnet-x64.exe
C:\Program Files (x86)\dotnet
    dotnet.exe
    dotnet-x86.exe
```

So first on path would still win for `dotnet`, but you could do `dotnet-x86 <app>` or `dotnet-x64` app with both on your path.

**Comment by markusschaber** [comment]
@steveharter We have several machines (Dev and QS) which are supposted to run both 32 and 64 bit code.
And some projects are forced to x86 only, as no x64 variant of said native libs exists yet - but changing the PATH order hardwires all projects to x86, ignoring the fact that we set CLI or X64 as architecture on those other projects, where we even have some test cases which actually need 64 bit.

This forced us to do PATH magic from outside (our CI system before calling the tests, or restarting Visual Studio while developing) as wee need to run tests and applications in both x86 and x64 in the same machines
