### ISSUE TITLE
Snappy - Authenticating via websockets results in exceptions

### ISSUE THREAD

**Issue by egee-irl** [dotnet/core-setup#4319]
## Steps to reproduce
1) Install latest SDK via Snap
2) Write some code that authenticates via Websocket
3) Run said code via `dotnet run`

## Expected  behavior
Application is able to authenticate and connect to websocket normally

## Actual behavior
Application throws two exceptions
1) `System.Net.Http.HttpRequestException: The SSL connection could not be established`
2) `System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

## Environment data
I'm running this code on [Solus](https://solus-project.com/) (a Snap-friendly Linux distro). I've ruled-out a distro-specific issue because using the binaries directly work fine.

dotnet --info output
`
```
egee@workstation ~/Source/suzy/Androgee $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     solus
 OS Version:  3.9999
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/19/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/snap/dotnet-sdk/19/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/snap/dotnet-sdk/19/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/snap/dotnet-sdk/19/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/snap/dotnet-sdk/19/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
`

**Comment by leecow** [comment]
@egee-irl - This issue is quite old so hopefully you've found a way past the trouble already. If not, could you try setting the following prior to running your app? There are some situations where the runtime is not correctly resolving certs and setting the environment variable explicitly generally corrects the situation. I just tested this on Solus 3.999 with the lastest .NET Core (runtime 2.2.1 and sdk 2.2.103)

export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_DIR=/dev/null

cc @bartonjs

**Comment by leecow** [comment]
@egee-irl - This issue is quite old so hopefully you've found a way past the trouble already. If not, could you try setting the following prior to running your app? There are some situations where the runtime is not correctly resolving certs and setting the environment variable explicitly generally corrects the situation. I just tested this on Solus 3.999 with the lastest .NET Core (runtime 2.2.1 and sdk 2.2.103)

export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_DIR=/dev/null

cc @bartonjs
