### ISSUE TITLE
Failed to bind to CoreCLR at '/opt/dotnet/shared/Microsoft.NETCore.App/2.1.1/libcoreclr.so' in dotnet new

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#4368]
_From @RZProf on July 12, 2018 20:54_

I have an error
```
Failed to load �P�U, error: /usr/lib/libm.so.6: versionGLIBC_2.27' not found (required by /opt/dotnet/shared/Microsoft.NETCore.App/2.1.1/libcoreclr.so)
Failed to bind to CoreCLR at '/opt/dotnet/shared/Microsoft.NETCore.App/2.1.1/libcoreclr.so'
```
i dont know what is it!!!

_Copied from original issue: dotnet/cli#9655_

**Comment by nguerrera** [comment]
This looks like a missing dependency of the runtime. What operating system is this? How was the runtime (or SDK containing the runtime) installed.

**Comment by RZProf** [comment]
I use Arch Linux and install runtime and SDK from Arch repository (pacman).

**Comment by frode** [comment]
I have the same issue on Debian 9:

username@hostname:/var/www/debian.9-x64/publish$ dotnet myprojectfile.dll
Failed to load �ݿ, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/var/www/debian.9-x64/publish/libcoreclr.so'

**Comment by HirbodBehnam** [comment]
Thanks @frode that solved the issue for me in CentOS 7. Keep in mind that in CentOS, the package name is **libunwind-devel**.

 You can install it with `sudo yum install -y libunwind-devel`

**Comment by mattmon1** [comment]
I experiencing this issue when I run dotnet *.dll on Alpine Linux 3.8.1 with .NET Core 2.1.2.

I installed the libundwind package by running:
	apk add libunwind-dev

![apk info 2018-11-14_11-13-08](https://user-images.githubusercontent.com/35613928/48504145-a8414680-e809-11e8-8683-ac6a7c6fd6ac.png)

Unfortunately, I'm still getting the error when I run dotnet *.dll

![apk add dotnet exec 2018-11-14_11-10-44](https://user-images.githubusercontent.com/35613928/48504163-b1321800-e809-11e8-8061-6692a00328f0.png)

Just reaching out to the community to see if you have any insights for resolving?

**Comment by SinxHe** [comment]
i have the same problam

**Comment by dagood** [comment]
I'm closing this issue because it's about an Arch Linux package, which is not maintained by Microsoft. It looks like bugs on that package are tracked at https://bugs.archlinux.org/?project=5&string=dotnet-sdk. The package has also been flagged as out of date on 2019-08-02, according to https://www.archlinux.org/packages/community/x86_64/dotnet-sdk/. (Yeah, this thread is fairly old in the first place--sorry we weren't able to respond to it sooner.)

If anyone on this thread is still having problems, please log a distro-specific issue (e.g. CentOS) so we can track this better. I don't think this should be a problem anymore--I don't hit it when I try installing our packages from scratch, at least. The `dotnet-runtime-deps-*.*` package we produce for each distro should contain the correct dependencies to let .NET Core run.
