### ISSUE TITLE
Cannot install .Net Core SDK (Ubuntu)

### ISSUE THREAD

**Issue by SherifRefaat** [dotnet/core-setup#4425]
## Steps to reproduce
Attempt to install .net core on Ubuntu-1804-bionic-64-minimal
RAM: 64 GB DDR4
HDD: 2 x 500 GB SATA 6 Gb/s SSD

## Expected  behavior
.net core install

## Actual behavior
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1.4
E: Couldn't find any package by glob 'dotnet-sdk-2.1.4'
E: Couldn't find any package by regex 'dotnet-sdk-2.1.4'

Also, calling `dotnet` 
Produce this:
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

## Environment data
Linux Ubuntu-1804-bionic-64-minimal 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by leecow** [comment]
First of all, just checking that followed the steps at https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current? Second, the earliest SDK version available on the 18.04 feed is 2.1.105 from April. 2.1.4 was released in January. 

Do you need the 2.0 runtime or are you looking for the latest? If it's the latest then `apt install dotnet-sdk-2.1` is the way to go.

**Comment by SherifRefaat** [comment]
@leecow I followed the steps (again) in the link included, here is the output:

![2018_08_02_17_25_02_root_ubuntu_1804_bionic_64_minimal_fulfilment_platform_task_api](https://user-images.githubusercontent.com/11178713/43594056-8ba0160a-9679-11e8-8050-aac2f226e761.jpg)

**Comment by leecow** [comment]
Thanks, steps look good. I don't see a `packages.microsoft.com` hit in the `apt-get update` output which is why you're not seeing the packages. Next question is why is that happening? You can install from tarball in the meantime while this bit gets figured out. 

* [system pre-reqs](https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md)
* [binary install and setup step](https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-linux-x64-binaries)

**Comment by SherifRefaat** [comment]
@leecow I think this is why: 
![2018_08_02_17_25_02_root_ubuntu_1804_bionic_64_minimal_fulfilment_platform_task_api_2](https://user-images.githubusercontent.com/11178713/43612017-3f010c6e-96ab-11e8-82be-b64b479b2637.jpg)

Is this can be ignored or not?

**Comment by leecow** [comment]
The 404 is the problem. May be a CDN issue in your region. Where are you? I can check with the Azure folks to see if there have been identifiable issues.

**Comment by SherifRefaat** [comment]
@leecow Finland

**Comment by leecow** [comment]
Thanks, checking with the repo owners to see if they can find anything.

**Comment by mbearup** [comment]
@SherifRefaat it looks like your list file (/etc/apt/sources.list.d/microsoft-prod.list) is broken - its contents should be:
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main

When I install the client package this is what I get and it works. I also see the .list file (https://packages.microsoft.com/config/ubuntu/18.04/prod.list) is correct. I cannot repro your issue (where /etc/apt/sources.list.d/microsoft-prod.list has the wrong content) but if you find that installing the client package continues to give you problems let us know.

**Comment by SherifRefaat** [comment]
I browsed '/etc/apt/sources.list.d/' to look for 'microsoft-prod.list' and found it but its name was slightly different it was 'microsoft-prod.list.save' so I renamed it to remove the '.save'.
The file content was:
![bionic-64-minimal](https://user-images.githubusercontent.com/11178713/43669083-ca7ca00c-9780-11e8-9c9d-c0a9151dd794.jpg)

Then ran 'apt-get update' and got the following
![bionic-64-minimal_2](https://user-images.githubusercontent.com/11178713/43669127-fe396c18-9780-11e8-8b15-82922bddfbe1.jpg)

So I searched and followed the advice of the second comment here: https://github.com/Microsoft/vscode/issues/27970

Then ran 'apt-get update' again I got the following:
![bionic-64-minimal_3](https://user-images.githubusercontent.com/11178713/43669198-83e3b896-9781-11e8-96e9-da57837eac12.jpg)

Then I ran 'apt-get install dotnet-sdk-2.1' and I got the following:
![bionic-64-minimal_4](https://user-images.githubusercontent.com/11178713/43669221-bb52cd30-9781-11e8-9c79-007340588914.jpg)

@leecow @mbearup What do you think?

**Comment by mbearup** [comment]
1. For the initial issue (.save file) this usually occurs if a package upgrade/install occurs but a manually created/edited file is already there. E.g. if microsoft-prod.list was already there before you tried to install the client package. The contents of the .save file look correct.
2. For the second issue (GPG keys missing) this implies some kind of issue with installing the client package, since the client GPG keys get installed by the client package.
3. The second screenshot shows that you have two instances of the repo configured - one is correct (ubuntu/18.04/prod) and one is incorrect (config/ubuntu/18.04/packages-microsoft-prod.deb). Where this came from is a mystery, because our client package and .list file both have the right URL.
4. Based on the steps in your link and the 3rd screenshot it looks like you successful imported the keys (via curl … gpg --dearmor) and Hit #11 shows you're successfully talking to the repo. But that pesky config/ubuntu/18.04 url is causing errors (Ign #9/Err#12). At this point you're functional but will see errors with apt-get update.
5. The 4th screenshot shows you're successfully getting the package (using "Hit#11" from 3rd screenshot). 

In summary, it seems like something with the system was not "clean" prior to these steps, because the .save file would only get generated if apt created it, and the missing GPG keys imply that the client package was not previously installed successfully. Further, I don't see the config/ubuntu/18.04/packages-microsoft-prod.deb url in our client package or .list file so I don't see how you got that enabled. I'm struggling to think of a precise scenario that would generate the first 2 symptoms, let alone the bad URL.
To clean up your system (and perhaps inform how we got here) you could take a look at the other .list files under /etc/apt/sources.list.d to determine where the config/ubuntu/18.04/packages-microsoft-prod.deb entry resides. Removing this will eliminate the errors you see with apt-get update.

**Comment by mbearup** [comment]
Just for clarification, I've inspected both the client package and the .list file. If you see something different let me know.
`$ wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
$ mkdir data-root
$ cat data-root/etc/apt/sources.list.d/microsoft-prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
$ sha256sum packages-microsoft-prod.deb
54fb378267b8492f697a4d4f4ce3b339da750da00173f154d95701d81399aa6c  packages-microsoft-prod.deb

$ wget https://packages.microsoft.com/config/ubuntu/18.04/prod.list
$ cat prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
$ sha256sum prod.list
f2d99f90bb4de475736aadd4899b1459b4eb22022bd40ab1ada887e90286e804  prod.list`

I also performed a hashsum check on the files on our regional mirror in your location and they match, so I don't have any reason to suspect that those files are somehow corrupted.

**Comment by leecow** [comment]
`grep -r config /etc/apt/sources.list.d/` is a quick way to list any file containing 'config' in the sources.list.d directory.

**Comment by SherifRefaat** [comment]
Okay! after scratching my head for a lot of time now. I 'heroically' I deleted the following
1. sources.list.save
2. source.list.save

Then, edited /etc/apt/sources.list
to remove this source line: `https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb` and replaced it with `deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main`

Then, ran `apt-get update` and got the following line
`
Hit:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
`
which is the only URL that is registered with Microsoft.

@leecow @mbearup What do you think?

**Comment by leecow** [comment]
Looks like you should be seeing the packages now. Are you still seeing errors?

**Comment by SherifRefaat** [comment]
@leecow No.
