### ISSUE TITLE
how to define the path list to search the dll file when run dotnet application

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#4710]
_From @wangyugui on October 28, 2018 1:21_

## Steps to reproduce

```
>dotnet dotnet/hello/bin/Release/netcoreapp2.1/hello.dll
works well.

but I failed to find a way to run it as 'dotnet hello.dll'.
Is there some environment var such as $PATH or $LD_LIBRARY_PATH?

Sorry that it is a simple question, but I failed to find the result by google.
```

_Copied from original issue: dotnet/cli#10247_

**Comment by vitek-karas** [comment]
On unixes `dotnet` uses the `realpath` function to convert the parameter to a file path. My understanding is that it basically takes the current working directory and combines it with the specified relative path. `dotnet.exe` itself doesn't add any additional logic to this.
You can `cd`, `dotnet`, `cd back` , but it's not as nice.
I don't think there's a way to do exactly what you're asking for.

**Comment by vitek-karas** [comment]
Another option might be to publish the app to the specific RID, in which case it should get an executable (the folder with the app should contain not just the `.dll` but also an executable with the same name). You can then run the app by just running the executable directly. And then one would follow the OS rules, thus `$PATH` should work.

**Comment by vitek-karas** [comment]
If you install the [.NET Core 2.2 Preview](https://www.microsoft.com/net/download/dotnet-core/2.2) you can run the publish with `--self-contained=false`. That will make the app basically the same as before (small) and only add the executable. Behavior should still be the same.

The difference is that self-contained app includes the runtime and all the frameworks, that's why it's so big. You can run it without .NET Core installed on the machine. With the `--self-contained=false` you will get a framework dependent app, which means it only contains the app's binaries but it requires the .NET Core installed on the machine so that it can use it to get the runtime and frameworks.

**Comment by wangyugui** [comment]
I have tested .NET Core 2.2 Preview3.

Thanks for this nice new feature.
