### ISSUE TITLE
Support semver V2 in the host

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#4795]
With the repos moving to arcade, all versions are moving to semver v2 as well.

This will likely happen for corefx/core-setup. This will happen for core-sdk and will happen for asp.net as well.

The host should be able to handle the runtimes/sdks with this new version scheme.

cc @natemcmaster

**Comment by livarcocc** [comment]
cc @leecow

**Comment by leecow** [comment]
@jeffschwMSFT - Is this work already scheduled?

**Comment by jeffschwMSFT** [comment]
What is semver V2? 

CC @sdmaclea

**Comment by natemcmaster** [comment]
https://semver.org/spec/v2.0.0.html and https://blog.nuget.org/20140924/supporting-semver-2.0.0.html are good material to read on this.

Probably the most important difference: the pre-release labels in SemVer2.0 are allowed to contain a dot, which affects sorting rules. Example: `3.0.0-preview.15866.6` (semver 2) vs `3.0.0-preview-15866-06` (semver 1).

There are a few others things in semver 2.0, like version metdata, which may not be as important to support. For example, NuGet supports a semver2.0 package version like this: `3.0.0-preview.15866.6+commitsha-abcxyz`. They normalize the verison by ignoring the `+commitsha-abcxyz` part.

**Comment by sdmaclea** [comment]
@natemcmaster The aspnet/AspNetCore#4171 issue mentions that it is blocked moving to semver v2 until this is resolved.  Can you explain the issue further?  Is the version sorting broken in the host?

**Comment by natemcmaster** [comment]
@sdmaclea yes, I don't want to move us to semver v2 until we're clear that it is a supported scenario. Here is one scenario that is broken today:

semver v2 requires (1) no leading zeros in numeric identifiers and (2) pre-release labels should be split on dots, with numeric identifiers sorted by numeric value, not ASCII value. So, if I only have `Microsoft.NETCore.App/3.0.0-preview.10` installed and an app that depends on `Microsoft.NETCore.App/3.0.0-preview.9`, I would expect the host to rollforward to 3.0.0-preview.10, but currently it fails.

> 
> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview.9' was not found.
>   - Check application dependencies and target a framework version installed at:
>       C:\Users\namc\.dotnet\x64\
>   - Installing .NET Core prerequisites might help resolve this problem:
>       https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>   - The .NET Core framework and SDK can be installed from:
>       https://aka.ms/dotnet-download
>   - The following versions are installed:
>       3.0.0-preview.10 at [C:\Users\namc\.dotnet\x64\shared\Microsoft.NETCore.App]

**Comment by vitek-karas** [comment]
The only tricky bit will be that we will have to keep supporting the old versioning scheme in the host code as well (since `hostfxr` must be able to find and resolve <3.0 frameworks).

In theory there's one case where this is impossible to do fully backward compatible: 1.0.0-9 and 1.0.0-10
In the v1 of semver this would compare in the order 1.0.0-10 < 1.0.0-9. In the v2 of semver this would compare as 1.0.0-9 < 1.0.0-10. And there's no way to tell which semver the version string is using.

That said, introducing this "breaking" change should not cause us trouble, since .NET Core should have never used just numerical characters in the preview portion of the version so far.

Other than this, we should just do this, as there's doesn't seem to be any downside. Assuming all versions so far followed the semver v1 spec. Obviously version strings which don't follow the spec will use undefined order.
