### ISSUE TITLE
AppBaseCompilationAssemblyResolver does not resolve assembly when basePath replaces spaces with %20

### ISSUE THREAD

**Issue by woksin** [dotnet/core-setup#4969]
## Steps to reproduce
Try resolve a CompilationLibrary with a:
```
new AppBaseCompilationAssemblyResolver(basePath);
``` 
where basePath is a path where spaces are replaced with %20 (new Uri().AbsolutePath does this)
## Expected  behavior
I expect it to find the assembly because I can see that the .dlls that I want is in that base path 
However this could be expected behaviour? But in my opionion I think that it should understand strings with %20
## Actual behavior
It failes resolving, does not populate the list given in as argument to TryResolveAssemblyPaths

## Environment data

**Comment by eerhardt** [comment]
We use the `basePath` to eventually pass into `File.Exists`, which also doesn't handle `%20` characters. Here's a small repro:

```C#
        static void Main(string[] args)
        {
            string filePath = @"C:\Program Files\dotnet\dotnet.exe";
            var uri = new Uri(filePath);

            Console.WriteLine($"Exists(filePath) {File.Exists(filePath)}");
            Console.WriteLine($"Exists(uri.AbsolutePath) {File.Exists(uri.AbsolutePath)}");
        }
```

Prints

```

**Comment by JeremyKuhne** [comment]
> is there an expectation that File.Exists should handle %20 characters? 

No, because those characters are valid. You can have a file named `%20.txt` so even if we wanted to add "smarts" here we couldn't. (For the record we do our best to stay out of the way of interpreting paths- we let the OS do as much as possible for cross platform and future compat.)

A `Uri` is different than a path. The way it handles input can be confusing. It expects, for example, unescaped local path if you don't have a scheme.

``` C#
string path = Path.Join(Path.GetTempPath(), @"%20.txt");
File.Create(path).Dispose();
Console.WriteLine($"'{path}' exists: {File.Exists(path)}");
Uri uri = new Uri(path);
Console.WriteLine($"Uri local path: '{uri.LocalPath}'");
Console.WriteLine($"Uri absolute uri: '{uri.AbsoluteUri}'");
Uri uri2 = new Uri(uri.AbsoluteUri);
Console.WriteLine($"Uri2 local path: '{uri2.LocalPath}'");
Console.WriteLine($"Uri2 absolute uri: '{uri2.AbsoluteUri}'");
```

Output:

```
'C:\Users\jerem\AppData\Local\Temp\%20.txt' exists: True
Uri local path: 'C:\Users\jerem\AppData\Local\Temp\%20.txt'
Uri absolute uri: 'file:///C:/Users/jerem/AppData/Local/Temp/%2520.txt'
Uri2 local path: 'C:\Users\jerem\AppData\Local\Temp\%20.txt'
Uri2 absolute uri: 'file:///C:/Users/jerem/AppData/Local/Temp/%2520.txt'
```

In general it is not the best idea to use 'Uri' for local paths. 'Uri' does not play well with device paths and alternate data streams on Windows for example. This is hard to fix without breaking existing apps.

If you do use 'Uri' for local paths you should **always** call `Path.GetFullPath()` on your paths before constructing a 'Uri' around them. Even better: escape it after that (with `Uri.EscapeDataString`) and add the `file:///` header yourself.

**Comment by eerhardt** [comment]
@woksin - I hope @JeremyKuhne's explanation helps. We won't be able to change this in `AppBaseCompilationAssemblyResolver` since it is just relying on the file system under the covers. Let us know if something doesn't make sense here.

Closing.
