### ISSUE TITLE
AppHost Pack: netcoreapp packaging

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5020]

**Comment by nguerrera** [comment]
@dagood I am wondering if the apphost packs can be prioritized.

It is essentially a rename (*) of `runtime.[rid].Microsoft.NETCore.DotNetAppHost` to `Microsoft.NETCore.App.Host.[rid]` (the aphost.exe, comhost.dll, ijwhost.dll) go in the same `runtimes/[rid]/native` folder. No extra data files are needed.

(*) But please keep both for some period of time to avoid a hard breaking change.

Plus the change of package type to DotnetPlatform, plus an installer like the targeting pack.

I would prioritize this over finalized runtime packs, because this blocks us from having offline support whereas the runtime packs will always be from nuget.

I had been hoping for offline to come online in P4, but we're probably too close to the cutoff for that now. Can we track this for P5?

**Comment by dagood** [comment]
Yes, putting this at the top of the stack. (Runtime packs were next up on the 3.0 backlog. 😄)

Thanks for the context and info about what's expected in it, too, that's helpful. Hadn't looked into this pack yet.
