### ISSUE TITLE
ARM and ARM64 legs failing

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/core-setup#5052]
## Steps to reproduce
Open PR with valid change

## Expected  behavior
PR passes

## Actual behavior
ARM & ARM64 legs fail

They fail to build on ARM because the machines don't have the right C++ compiler

**Comment by sdmaclea** [comment]
Observed on #4953, #5049, and #5050 

@dagood If you are not the right owner of this, can you please assign to the correct person.

/cc @vitek-karas

**Comment by MattGal** [comment]
I TAL'ed, and I don't think that the machine setup was the issue, rather we need newer workloads installed:


Success from 1/25:
```
2019-01-25T08:44:21.6496751Z   -- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.
2019-01-25T08:44:37.3354283Z   -- The C compiler identification is MSVC 19.15.26730.0
2019-01-25T08:44:40.2771952Z   -- The CXX compiler identification is MSVC 19.15.26730.0
```

Fail from today:
```
2019-01-28T15:47:25.7901790Z   -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.
2019-01-28T15:47:38.4503233Z   -- The C compiler identification is unknown
2019-01-28T15:47:42.6763084Z   -- The CXX compiler identification is unknown
```
... my theory being that moving the Windows SDK from 10.0.17134.0  to 10.0.17763.0 requires a different VS workload to be installed for the MSVC compiler to support it.

Details about what's supposed to be on the machines can be seen at https://dev.azure.com/dnceng/public/_settings/agentqueues?queueId=14&_a=details 

Options here are going to be: (definitely recommend starting w/ 1)

1. Email VSTS CI Experts and ask to have more of the 10.0.17763.0  SDK workloads added to their machines
2. Bootstrap the MSVC++ dependencies with the build and pass them in to the CMake command line.
3. Move to a non-hosted pool and use dnceng issues to get things updated.

**Comment by dagood** [comment]
Thanks for looking into it! And for the details page, hadn't noticed those before.

I'm going to be able to work on resolving this Wednesday.

**Comment by dagood** [comment]
This should be fixed now!

https://github.com/dotnet/core-setup/pull/5071 moves these legs to a core-eng self-hosted agent pool. It got green CI in all legs. There's an email thread about fixing the hosted pool, and moving back to it, since hosted pools are typically much more reliable. Doing that (and generally moving CI legs to hosted pools) is tracked by https://github.com/dotnet/core-setup/issues/4997.

**Comment by dagood** [comment]
Adding some details from the thread:

The agent configuration issue was a known bug fixed with https://github.com/Microsoft/azure-pipelines-image-generation/pull/665, which is now waiting to be deployed. Missing components were:
* Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre
* Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre

Another way to get the missing VS components is to run the VS installer with `--add` for those components. ([Installer doc](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017).) The installer is located at `C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe` in the hosted agent.

(Keeping the current workaround for now. Once the fix is deployed we can simply revert https://github.com/dotnet/core-setup/pull/5071 to use the hosted pool again.)
