### ISSUE TITLE
Cannot resolve runtime and native assets from dependency context of a class library

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#635]
Moving from https://github.com/dotnet/cli/issues/4005 on behalf of @natemcmaster.

-----

I am attempting to solve the problem of creating an AssemblyLoadContext from a class library project (https://github.com/aspnet/EntityFramework/issues/5320) with only 3 inputs: dependency context, nuget package directory, and application base path. (NB: no project context)
## Problem

The build trims "runtimeTargets" from the deps.json file. In order to execute code from an ALC, we need all runtime and native assets.
## Steps to reproduce

Create and compile netstandard project

``` c#
public class Class1 {}
```

``` json
{
    "dependencies": {
        "System.Data.SqlClient": "4.1.0"
    },
    "frameworks": {
        "netstandard1.3": {}
    }
}
```
## Expected

``` json
  "runtime.native.System.Data.SqlClient.sni/4.0.0": {
        "dependencies": {
          "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni": "4.0.1",
          "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni": "4.0.1"
        }
      },
      "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni/4.0.1": {
        "runtimeTargets": {
          "runtimes/win7-x64/native/sni.dll": {
            "rid": "win7-x64",
            "assetType": "native"
          }
        }
      },
      "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni/4.0.1": {
        "runtimeTargets": {
          "runtimes/win7-x86/native/sni.dll": {
            "rid": "win7-x86",
            "assetType": "native"
          }
        }
      },
```
## Actual

``` json
      "runtime.native.System.Data.SqlClient.sni/4.0.0": {
        "dependencies": {
          "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni": "4.0.1",
          "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni": "4.0.1"
        }
      },

      "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni/4.0.1": {},
      "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni/4.0.1": {},
```

cc @davidfowl

**Comment by gkhanna79** [comment]
@piotrpMSFT Why should this be moved to Core-Setup and not remain in CLI as this talks about build generated artifacts being trimmed?

CC @schellap

**Comment by natemcmaster** [comment]
Ping. Can we revisit this again?

re @gkhanna79 I believe @piotrpMSFT put the issue here because this is where DependencyContext code lives, even though deps.json generation is now in dotnet/sdk.

**Comment by gkhanna79** [comment]
DependencyContext issues are being looked into by @livarcocc and @eerhardt. 

@livarcocc Can you PTAL?

CC @schellap @ramarag

**Comment by natemcmaster** [comment]
cc @pranavkm @bricelam - if this gets resolved, it _might_ re-open the door for design-time tooling to use AssemblyLoadContext.

**Comment by gkhanna79** [comment]
CC @eerhardt

**Comment by eerhardt** [comment]
I've spoken with @ericstj in the past on this type of situation.  In short, what you are trying to do is not supported.

The dependencies of libraries that target `netstandard` change between build-time and runtime.  More correctly, the dependencies change between the build-time of the library and the build-time of the composing application, which actually knows which runnable .NET platform it is targeting.

Using your above example (assuming the library you are creating is called `Foo`):

When `Foo` is built, it only knows that it is targeting `netstandard1.3`, so it can only pick assets from its dependencies using the `netstandard1.3` TFM.

However, the `System.Data.SqlClient` package has assets for both `netstandard1.3` and `net46`:

![image](https://cloud.githubusercontent.com/assets/8291187/23627390/268117f8-0276-11e7-8aa4-1911620cefbf.png)

How would the build-time of `Foo` know which `System.Data.SqlClient` runtime assets to use?  It can't because it doesn't know if it is going to be used on `net46` or on `netcoreapp` until an actual application composes it using a "runnable" TFM.

**Comment by natemcmaster** [comment]
Closing as we don't need this anymore. We worked around it by using project.asset.json to get the info we need about runtimes.
