### ISSUE TITLE
hostfxr_initialize_for_app doesn't work with an exe for app_path

### ISSUE THREAD

**Issue by jkotalik** [dotnet/core-setup#6388]
## Steps to reproduce

Calling hostfxr_initialize_for_app with the exe name of the application eventually hits an error:
```
An assembly specified in the application dependencies manifest (InProcessWebSite.deps.json) has already been found but with a different file extension:
     package: 'InProcessWebSite', version: '3.0.0-preview6-t000'
     path: 'InProcessWebSite.dll'
     previously found assembly: \InProcessWebSite.exe'
 Failed to initialize context for app: \InProcessWebSite.exe. Error code: 0x8000808c
```
## Expected  behavior
Calling hostfxr_main works in this scenario.

**Comment by jkotalik** [comment]
Few examples of other arguments that worked when calling hostfxr_main that don't work when calling initialize_for_app:
args[0] = C:\Example\dotnet\dotnet.exe args[1]=MyApp.Dll, we have to put dotnet into the initialize parameters now.
args[0] = C:\Example\MyApp.exe

**Comment by jkotalik** [comment]
Also, when calling hostfxr_main, the can be a parameters called `exec` too.

For example, args[0] = C:\Example\dotnet\dotnet.exe, args[1] = 'exec', args[2] = MyApp.dll

**Comment by vitek-karas** [comment]
At least for now it's intentional that we don't support the full command line interface of the muxer through the new hostfxr APIs. For example running SDK and such all of which is technically supported by `hostfxr_main`.

It should support the host options like `--roll-forward`, but in a way that's a necessary evil. Ideally I think the command line args passed to the `hostfxr_initialize_for_app` should be the arguments for the application itself.

I personally would like to keep the command line parsing in `hostfxr_initialize_for_app` as simple as possible - to increase its predictability. The current command line parsing for the muxer is rather confusing and I would like to steer away from it for now (if possible).

I assume your scenario is that you take a command line to launch an app "verbatim" and pass it on, right?

Specifically the `dotnet.exe` case is very weird to me. The native hosting APIs are not the muxer, so I would argue they should not recognize the muxer as anything special.

**Comment by jkotalik** [comment]
> I assume your scenario is that you take a command line to launch an app "verbatim" and pass it on, right?

Yes, that is correct. I think we need to determine whether what responsibilities `hostfxr_initialize_for_app` should have, specifically things that normally are done in the muxer. For example, the `exec` scenario is hard coded in the muxer: https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/fxr/fx_muxer.cpp#L741. We can handle it on our side, but it adds extra complexity that shouldn't be necessary.

I think a nice compromise that we can have here is to add a new api to hostfxr that translates argc/argv into the new initialize parameters
```
// Proposed Hostfxr API to support ANCM scenarios

int hostfxr_parse_command_line(
	// Inputs
	int argc,
	const char_t * argv[],

	// Outputs
	int* app_argc,
	const char_t ** app_argv[],
	const char_t ** app_path,
	const hostfx_initialize_parameters* app_parameters)
```
 We can discuss this more shortly.

**Comment by jkotalik** [comment]
Another options would be to have a new hostfxr_initialize_parameters that takes in argc and argv only.

**Comment by elinor-fung** [comment]
Based on our conversations, my plan is to add:
```
int hostfxr_initialize_for_dotnet_command_line(
    int argc,
    const pal::char_t *argv[],
    const hostfxr_initialize_parameters * parameters,
    /*out*/ hostfxr_handle * host_context_handle)
```
- `argc` / `argv` - command line arguments for running an application as if through the dotnet executable
- `parameters` - Optional. Additional parameters for initialization
- `host_context_handle` - Output. Populated with the initialized host context on success.

It will not support SDK commands.

It will only support arguments for running an application as through the muxer. If argv is:
- `App.dll`, `arg1`, `arg2`
- `exec`, `App.dll`, `arg1`, `arg2`

The function will initialize for the app `App.dll` and will pass `arg1` and `arg2` to the app when `hostfxr_run_app` is called.

Passing an apphost exe is not supported. If argv is:
- `App.exe`, `arg1`, `arg2`

The function will fail to initialize (just like calling `dotnet.exe App.exe` would fail).
