### ISSUE TITLE
[Ubuntu 19.04] NETSDK1056: Project is targeting runtime 'ubuntu.19.04-x64' but did not resolve any runtime-specific packages

### ISSUE THREAD

**Issue by khteh** [dotnet/core-setup#6550]
## Steps to reproduce
Bring up environment:
```
$ wget https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-deps-latest-x64.deb
$ sudo apt install dotnet-runtime-deps-latest-x64.deb
$ sudo apt update
$ sudo apt install dotnet-runtime-deps-2.2
$ sudo apt install dotnet-runtime-deps-3.0
```
Build:
```
$ cd project
$ dotnet build -c Release  --runtime ubuntu.19.04-x64 --no-restore src
```

## Expected  behavior
Build without error

## Actual behavior
Build error:
```
error : NETSDK1056: Project is targeting runtime 'ubuntu.19.04-x64' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
```

## Environment data
```
$ dotnet --version
2.2.204
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by dagood** [comment]
@ericstj, @bartonjs, is this because https://github.com/dotnet/corefx/pull/37269 hasn't been released yet to add 19.04 to the RID graph? Does this issue belong in CoreFX?

**Comment by ericstj** [comment]
/cc @wtgodbe 

That sounds right.  I would imagine that this is tied to actually releasing a 2.2 with an updated RID graph.  Not sure I would open anything in CoreFx since I don't believe there is work left to do there.  I imagine we'd want to test the scenario from the 2.2 servicing builds or provide instructions to the customer around how to pick those up.

**Comment by khteh** [comment]
When should this runtime flag be used? Is it a general flag which applies to all use cases just to optimize the generated binaries for specific platform? Specifically, is it only used to build self-contained binaries or it can also be used to build app which runs on dotnet core SDK/Runtime?

**Comment by dagood** [comment]
https://docs.microsoft.com/en-us/dotnet/core/deploying has a nice overview of the types of deployment, and https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli describes how to accomplish them with the various SDK args. It's not accomplishing one specific thing, rather it's needed when the deployment method you're using requires some specific RID to know what to do.

Closing this issue because there's nothing needed for this in Core-Setup. The next servicing release including the 19.04 RID entry will be around July if nothing changes.
