### ISSUE TITLE
Missing Microsoft.NETCore.App.versions.txt in Microsoft.NETCore.App nuget package

### ISSUE THREAD

**Issue by kbaladurin** [dotnet/core-setup#6810]
Now Microsoft.NETCore.App nuget package (for example https://www.nuget.org/packages/Microsoft.NETCore.App/3.0.0-preview6-27804-01) doesn't contain `Microsoft.NETCore.App.versions.txt`. Is it expected? How can I get corresponding commit hash?

Thank you!

**Comment by kbaladurin** [comment]
cc @alpencolt @gbalykov
@jkotas PTAL

**Comment by dagood** [comment]
There's been some package shuffling in support of a 3.0 workaround that indirectly caused this: https://github.com/dotnet/core-setup/issues/5663. I don't think we'll necessarily keep creating this workaround package for future versions so it's worth exploring newer ways to get the info you're looking for.

You can still get the Core-Setup commit hash from the `Microsoft.NETCore.App` package description (shown on the Gallery and in the `nuspec` file in the extracted NuGet package):

```
A set of .NET APIs that are included in the default .NET Core application model. 
fdf81c6faf7c7e0463d191a3a1d36c25c201e5cb
When using NuGet 3.x this package requires at least version 3.4.
```

The `Microsoft.NETCore.App.versions.txt` file is still available in the runtime packages, like `runtime.win-x64.Microsoft.NETCore.App`.

@kbaladurin, can you describe why you're looking for this file in the package to see if there's some better way for you to get this info?

---

Related note: in 3.0, the `Microsoft.NETCore.App` nupkg is no longer a way to obtain the runtime. Check out https://github.com/dotnet/designs/pull/50 for an in depth look.

**Comment by kbaladurin** [comment]
@dagood thank you for the answer! I'm looking for the version file to get commit hash that used to build corresponding runtime package for Tizen OS.

**Comment by dagood** [comment]
Ah, wondered if that was it. 😄 

Ideally, you could get this data from the Build Asset Registry (BAR), but that isn't available publicly yet: https://github.com/dotnet/arcade/issues/1818.

In the meantime, other packages still have the versions file, just not `Microsoft.NETCore.App`, and/or you can change to use the commit hash in the nuspec.

One kind of new thing is that once you have the commit hash of Core-Setup, you can look at the commits of CoreCLR and CoreFX that commit uses here:

https://github.com/dotnet/core-setup/blob/da6c56ca21034650ac99b27ddfdcd28ce6e20547/eng/Version.Details.xml#L12-L15

https://github.com/dotnet/core-setup/blob/da6c56ca21034650ac99b27ddfdcd28ce6e20547/eng/Version.Details.xml#L100-L103

I'm not sure if it's practical for you to use that, but it's a subset of the info in BAR so it's a step towards the future.

Closing this issue because there's no plan to add it back to `Microsoft.NETCore.App` and there are some pretty easy ways to get this working again. (Or, it seems to me.)
