### ISSUE TITLE
Questions: Why is a reboot required after install of preview6?

### ISSUE THREAD

**Issue by batzen** [dotnet/core-setup#6813]
## Steps to reproduce
Download https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview6-windows-x64-installer and install.

## Expected  behavior
No reboot is required.

## Actual behavior
Reboot is required.

## Environment data
OS Version:                10.0.18362 N/A Build 18362

**Comment by dagood** [comment]
I believe this happens when some program's using a file that needs to be updated. The installer should have warned you about it, I think--I get this screen when I run a `dotnet` process and try to install the new version:

![image](https://user-images.githubusercontent.com/12819531/59460341-7c5c6280-8de4-11e9-8363-5162be78835e.png)

@batzen, do you know if you saw that screen, and which option you chose if so?
Can you share the install logs in `%temp%`?

Choosing to close the apps and clicking next worked for me. (The process I launched closed fine and the install succeeded without telling me I had to restart.) `Microsoft_.NET_Core_SDK_3.0.100_-_preview6_(x64)_20190613140547_002_dotnet_host_3.0.0_preview6_27804_01_win_x64.msi.log` tells me:

`MSI (s) (4C:24) [14:07:57:321]: RESTART MANAGER: Successfully shut down all applications in the service's session that held files in use.`

@joeloff, @johnbeisner, other ideas?

**Comment by joeloff** [comment]
No, files being used are the typical reason. Installers can explicitly force reboots, but we never do that. In either case, the logs should show that the MSI exited with code 3010 as opposed to 0, which will trigger a pending reboot. The bundle should be grabbing an installer mutex, but there's always a possibility that something like an OS update snuck in and is causing the reboot, but I don't think this is a likely scenario.

One change in 3.0 is that we are now upgrading within release bands. Previously if you had a 2.1.6 app running, installing 2.1.11 wouldn't cause a reboot because 2.1.11 and 2.1.6 runtimes can be installed SxS. In 3.0, we'll remove the previous preview and install a new one, making the files-in-use issue more prominent I think

**Comment by batzen** [comment]
@dagood There was no such question during installation and the logs don't say anything about shutting down all applications.
What i could find in the logs was `MsiSystemRebootPending = 1`. Does that mean the installer picks up an already pending reboot and shows the "Reboot" button because of that?

**Comment by dleeapho** [comment]
@joeloff any ideas on @batzen last question?

**Comment by joeloff** [comment]
Yes, though that flag isn't always set. See [this link](https://docs.microsoft.com/en-us/windows/desktop/Msi/msisystemrebootpending) Normally that flag is set if there's a pending rename on a file, but it's not always set.

With a bundle, previous MSIs in the chain could also indicate a reboot when they exit with 3010 instead of 0

If any MSI in the bundle exited with 3010, the UI might also display a restart option once all the packages have been installed.

**Comment by dagood** [comment]
Closing, I believe the question is answered. Reboot issues have come up again recently at #8546, however we unfortunately don't have much control over this. (More details there.)
