### ISSUE TITLE
Carry uCRT binaries app-local

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#736]
This is required to alleviate the dependency on an external installer (of CRT). This will be achieved in the following manner once @weshaggard has enabled a flat-file version of Microsoft.NETCore.App in  Core-Setup repo:

1) Pull in uCRT binaries in Microsoft.NETCore.App (flat-file) package
2) Update the installer to no longer chain into CRT installer.

CC @schellap @ramarag @Petermarcu

**Comment by ericstj** [comment]
Can you add details about specifically which files are required and on what versions of the OS?

**Comment by ericstj** [comment]
Also, it makes more sense to me that these get packaged in the CoreCLR repo.  That way they remain in sync with the actual dependencies that CoreCLR takes.  Putting this in core-setup feels to me like we're going to be in a place where CoreCLR makes an update and we need to *remember* make a corresponding update in core-setup to pick up newer bits that are in sync with what CoreCLR needs.

Adding stuff to the flat packages is trivial so that shouldn't be a deciding factor.  It's a one-time thing then gets automatically updated with maestro.  If you make it part of the CoreCLR package closure (as was done with API sets) then there isn't even a one-time hit.

**Comment by gkhanna79** [comment]
@wtgodbe Assigning this to you to finish the Core-Setup side of changes once the coreCLR package is merged in by Maestro.

@Petermarcu Do you have a change for it that you wish to merge?
