### ISSUE TITLE
Single EXE extractor path w/ AWS Lambda

### ISSUE THREAD

**Issue by stevemk14ebr** [dotnet/core-setup#7940]
## Steps to reproduce
Make a .net binary with /p:PublishSingleFile=true. Place this binary in an aws lambda bundle and invoke it. 

## Expected  behavior
It should extract all deps to a temporary directory and execute.

## Actual behavior
It attempts to extract to /var/tmp but fails as only /tmp is writable in lambda.

## Suggestion to fix
To get out of the box runability without setting DOTNET_BUNDLE_EXTRACT_BASE_DIR i propose to change this to /tmp/.net . Or perhaps there should be multiple attempts at common locations (/var/tmp, /tmp, same directory as binary, etc)

**Comment by am11** [comment]
Maybe a simple fix is to not consider `/var/tmp` at all following exactly what corefx does: https://github.com/dotnet/corefx/blob/d391103/src/Common/src/CoreLib/System/IO/Path.Unix.cs#L72-L85.

i.e. deleting these lines:
https://github.com/dotnet/core-setup/blob/9bb119b2a4b82d54e73669928a3b831cc07a1291/src/corehost/common/pal.unix.cpp#L311-L316

**Comment by swaroop-sridhar** [comment]
On systems where `/var/tmp` is available, we prefer to use it because it is expected to be [survive across system reboots](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s15.html) unlike `/tmp` directory.

The host currently tries `$TMPDIR`,  `/var/tmp`,  `/tmp` in that order. However, it only checks for existence, and not write-ability. So, that's the best fix in this scenario.

**Comment by am11** [comment]
What happens if `/tmp` is cleared; does it slow down the single-file app(s) startup significantly compared to if it was persisted? Does the implementation take advantage of this caching?

In some systems, `/tmp` has activity-based cleanup policy, as opposed to every reboot. For example, some systems have (configurable) policy to cleanup the tmp files only if they haven't been accessed in past N days.

**Comment by vitek-karas** [comment]
In the current implementation the single-file extracts all files to disk - this can be lot of data (100MB). The path into which it extracts is deterministic, so on a second run it looks if it's there and will avoid extraction if possible. This makes the second startup much faster (basically just like a non-single-file app). If the extract location is too volatile the benefit of doing this would be relatively low - most of the time the app would have to re-extract.

Note that the extraction can be really slow - several seconds even on fast SSDs, so this is a meaningful "optimization" if possible.

In the future when more data will be read from the single-file directly this will become less important, but we're not there yet.

**Comment by stevemk14ebr** [comment]
@swaroop-sridhar i think the working directory should be added to the end of that list. Additionally i think failover should occur if the extracted files fail to execute at all, rather than just writability. This would prevent future unforseen causes of execution failure (such as this case was)

**Comment by swaroop-sridhar** [comment]
Keeping the issue open until the fix is in 3.1 branch.

**Comment by swaroop-sridhar** [comment]
@stevemk14ebr I have a fix for the issue in master branch, and am about to port the change for the 3.1 release branch. 

I've tested the change on an ubuntu machine where `/var/tmp` is not writable but `/tmp` is.

Can you please help verify that the change works on your host system?
The change is not yet picked up by the [official builds](https://github.com/dotnet/core-sdk). So, I've created a [custom build of the .net core 3.0 SDK](https://1drv.ms/u/s!AsGXkwwufZishP1-jlJ0LLKx-njoBw?e=UJWnV7) with the fix applied. You can use this SDK to publish your app for testing.
Thank you very much.

**Comment by swaroop-sridhar** [comment]
Checked in to release/3.1  https://github.com/dotnet/core-setup/pull/8596
