### ISSUE TITLE
HelloWorldMVC Start-Up JIT Compiles Many Methods in the Shared FX

### ISSUE THREAD

**Issue by brianrob** [dotnet/core-setup#84]
Of particular interest are non-generic methods such as:

System.Reflection.Metadata.MetadataReader.get_IsAssembly()
System.Reflection.Metadata.AssemblyDefinition.get_Version()
System.Reflection.Metadata.AssemblyDefinition.get_Flags()
System.Reflection.Metadata.AssemblyDefinition.get_PublicKey()
System.Reflection.Metadata.AssemblyDefinition.get_Name()
System.Reflection.Metadata.AssemblyDefinition.get_Culture()

**Comment by JohnChen0** [comment]
The Ready-to-Run images included in current shared framework are partial NGen images, and do not contain native code for all possible methods. The `COMPlus_PartialNGen=0` environment variable isn't passed to CrossGen during shared framework build. The problem seems to be in the definition of `ExecSilent` method, which isn't passing the env to `ExecCore`.

**Comment by gkhanna79** [comment]
CC @brthor

**Comment by gkhanna79** [comment]
CC @schellap

**Comment by eerhardt** [comment]
Fixed by #92
