### ISSUE TITLE
"./build.cmd -t" is slow

### ISSUE THREAD

**Issue by am11** [dotnet/core-setup#8521]
```cmd
:: windows command prompt
git clone https://github.com/dotnet/core-setup --single-branch
cd core-setup
.\build.cmd -t
```

It took about 15-20 minutes to complete. When I reran it without any modifications, it still took a lot of time on <ins>re-</ins>restoring the test packages.

![image](https://user-images.githubusercontent.com/3840695/66613415-218a1a80-ebce-11e9-9892-27dbf9eb8f03.png)

Can it be optimized so it does not restore these huge packages each time?

**Comment by dagood** [comment]
This isn't re-restore, these restores are grabbing the just-built packages. These are test asset projects that the test code itself runs commands on to carry out the tests.

15-20 minutes is unusual... on the public PR validation machines, it took 41 seconds in a random `master` run I picked out. Since you're starting with a fresh repo, I don't have any ideas on the top of my head that could be causing this other than hardware. (Storage speed, probably?)

If you'd like to check out the logic, it's at https://github.com/dotnet/core-setup/blob/master/src/test/PrepareTestAssets/PrepareTestAssets.proj. Binlogs are also invaluable.

**Comment by am11** [comment]
During the run `./build.cmd` run, it seems like Antimalware Service from Windows Defender which is stealing CPU cycles.
Google images: high cpu antimalware service
seems like I am not the only one affected by its annoyance.. 😅

**Comment by dagood** [comment]
Ah... yeah, that probably does it. Exception rules are useful here, but it's hard to recommend that. 😛 (Exceptions aren't even always possible... I'm actually unable to add exceptions because I'm on Defender ATP and it's not managed by myself. Luckily it isn't quite so slow for me. I did modify the build to handle a particularly nasty case though: https://github.com/dotnet/core-setup/issues/6651.)

Closing because I don't think there's anything actionable here at the moment, but improvements are of course welcome if you can think of any.
