### ISSUE TITLE
Can --additionalprobingpath be used as an alternative to runtimeconfig.json?

### ISSUE THREAD

**Issue by am11** [dotnet/core-setup#8539]
Create a new app and build it:

```sh
dotnet new console --name without-runtimeconfig
cd $_
dotnet build
```

then delete the runtimeconfig.json file and execute the output dll directly (with `dotnet (1)`):

```sh
cd bin/Debug/netcoreapp3.0
rm without-runtimeconfig.runtimeconfig.json

dotnet without-runtimeconfig.dll
```

to get the following error:

> A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/work/without-runtimeconfig/bin/Debug/netcoreapp3.0/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /work/without-runtimeconfig/bin/Debug/netcoreapp3.0/without-runtimeconfig.runtimeconfig.json file specifying the appropriate framework.

at this point, can we specify the probing path for `libhostpolicy` via
<code>dotnet --additionalprobingpath <ins>&lt;something here></ins> without-runtimeconfig.dll</code>? If so, what would be the value of `--additionalprobingpath `. I tried with the following values:

(path reported by `dotnet --list-runtimes`)

* `$HOME/.dotnet/shared/Microsoft.NETCore.App/3.0.0` 
  * directory where libhostpolicy.{dll,dylib,so} actually exists
* `$HOME/.dotnet/shared/Microsoft.NETCore.App`
* `$HOME/.dotnet/shared`

but to no avail.

**Comment by vitek-karas** [comment]
The problem is not the probing path but ability to declare framework references. The app needs to be able to specify which frameworks to use (in your simple case it would be `Microsoft.NETCore.App`, but for other apps it might be ASP.NET or WindowsDesktop). The app also needs to be able to specify the minimal version for each framework reference.

Currently the command line does not have options to specify framework references. The only supported way to specify those is the `.runtimeconfig.json` (for framework dependent apps).

The end result is that the host thinks the app is self-contained (no `.runtimeconfig.json` means no framework references, so it must be self-contained). As such it searches the app's directory for `libhostpolicy.so` (among other things), since self-contained apps should have it there.

I'm curious what you're trying to achieve. Is it that you want to minimize the number of files the app has, or is it some other goal?

**Comment by am11** [comment]
Thanks! [&& sorry, it fell off my radar]

I think it would be great if we can specify `.runtimeconfig.json` values on command line, so the need of physical file is not required. If it is not feasible, then perhaps `--runtimeconfig-path` could be considered for `dotnet`? It would be an improvement, as we can use heredoc syntax to elide the need of physical file.

I was improving this answer https://stackoverflow.com/a/56133028 to make `csc` (alias) work with pure/only .NET Core installation on a system. The answer has been reduced to two steps `csc -out:hwapp.exe Program.cs` and (a one-time) `create_runtimeconfig hwapp`. I wanted to get rid of the latter by means of command line arg to `dotnet $CSCPATH /r:$NETSTANDARDPATH ` call (without overwriting the json file each time).

**Comment by vitek-karas** [comment]
There is `--runtimeconfig`, through which you get to specify the path to the `.runtimeconfig.json` file. I didn't try it in your scenario, but it should work.

**Comment by am11** [comment]
Thanks! Seems like `--runtimeconfig` used to be an option on top-level `dotnet` command, and now it is on `dotnet-exec`. Updated the answer with simple aliases: `csc <compiler-options> Program.cs` to build and `csc_run <exe-name>` to run, without requiring runtimeconfig (only targeting console apps / quick experiments). 8-)
