### ISSUE TITLE
Distribution from Windows Update

### ISSUE THREAD

**Issue by hez2010** [dotnet/core-setup#8861]
# Distribution from Windows Update
## Background
Both Linux and macOS have their own built-in package managers which can be used for upgrading .NET Core minor version.
For example, on Debian-based Linux system we can use `sudo apt upgrade` to upgrade .NET Core SDK/Runtime version.

However, on Windows, we have to download the newer version of .NET Core installer and install it manually, and if there're security fixes in a patch build, we may not be able to acquire it in time.

## Proposal
Distributing .NET Core on Windows Update for minor version upgrade, both for SDKs and Runtimes. 
For example, if a user has installed .NET Core 3.0 SDK or Runtime on his Windows system, Windows Update will provide the latest 3.0 SDK or Runtime patch upgrade for him automatically.

**Comment by dagood** [comment]
The overall scenario of keeping .NET Core up to date is tracked at https://github.com/dotnet/core/issues/1541, closing as a duplicate.

> Both Linux and macOS have their own built-in package managers

This is generally true, but there is no built in package manager on macOS, and Microsoft doesn't support any of the common package managers on that platform like Homebrew.

> Distributing .NET Core on Windows Update for minor version upgrade

It sounds like you actually mean for *patch* version upgrade. That is, 3.0.1 => 3.0.2 (patch) is ok for an autoupdate, but 3.0.1 => 3.1.1 (minor) is not ok because those need to be usable side-by-side.
